[package]
name = "canopy"
authors = ["Aldo Cortesi <aldo@corte.si>"]
version = "0.0.1"
edition = "2018"


[dependencies]
crossterm = "0.20.0"
pad = "0.1.6"
textwrap = "0.14.0"
color-backtrace = "0.5.1"
scopeguard = "1.1.0"

canopy-derive = { path = "../canopy-derive" }
thiserror = "1.0.24"
