[package]
name = "canopy-widgets"
authors = ["Aldo Cortesi <aldo@corte.si>"]
version = "0.0.1"
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[features]
default = ["editor", "terminal-widget", "graphics", "devtools"]
editor = ["dep:syntect"]
terminal-widget = ["dep:itty-core"]
graphics = ["dep:image", "dep:fontdue"]
devtools = ["dep:tracing-subscriber"]

[dependencies]
canopy = { path = "../canopy" }

# Widget-specific dependencies
textwrap.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
image = { version = "0.25.10", optional = true, default-features = false, features = [
    "gif",
    "jpeg",
    "png",
    "webp",
] }
ropey = "1.6.1"
syntect = { version = "5.3.0", optional = true }
tracing-subscriber = { workspace = true, optional = true }
fontdue = { version = "0.9.3", optional = true }
itty-core = { workspace = true, optional = true }

[dev-dependencies]
canopy = { path = "../canopy", features = ["testing"] }
criterion.workspace = true
proptest.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread"] }
itty-script.workspace = true


[[bench]]
name = "editor"
harness = false
required-features = ["editor"]

[[test]]
name = "logs_subscriber"
required-features = ["devtools"]

[[bench]]
name = "rendering"
harness = false

[lints]
workspace = true
