[package]
name = "canopy-widgets"
authors = ["Aldo Cortesi <aldo@corte.si>"]
version = "0.0.1"
edition.workspace = true
license.workspace = true

[dependencies]
canopy = { path = "../canopy" }

# Widget-specific dependencies
textwrap.workspace = true
unicode-width.workspace = true
unicode-segmentation.workspace = true
image = { version = "0.25.10", default-features = false, features = [
    "rayon",
    "bmp",
    "dds",
    "exr",
    "ff",
    "gif",
    "hdr",
    "ico",
    "jpeg",
    "png",
    "pnm",
    "qoi",
    "tga",
    "tiff",
    "webp",
] }
ropey = "1.6.1"
syntect = "5.3.0"
portable-pty = "0.9.0"
tracing-subscriber = "0.3.23"
fontdue = "0.9.3"
thiserror.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time", "sync"] }
itty-core.workspace = true

[dev-dependencies]
canopy = { path = "../canopy", features = ["testing"] }
criterion.workspace = true
itty-script.workspace = true
loom = "0.7.2"
proptest.workspace = true


[[bench]]
name = "editor"
harness = false

[[bench]]
name = "rendering"
harness = false

[lints]
workspace = true
