[package]
name = "todo"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lib]
doctest = false

[dependencies]
anyhow.workspace = true
canopy.workspace = true
canopy-mcp.workspace = true
canopy-widgets.workspace = true
clap.workspace = true
musq = { path = "../../../musq/crates/musq", default-features = false }
pollster = "1.0.1"
textwrap.workspace = true
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[dev-dependencies]
canopy = { workspace = true, features = ["testing"] }
futures.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros"] }

[lints]
workspace = true
