[package]
name = "canopy-examples"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
doctest = false

[dependencies]
canopy = { path = "../canopy" }
canopy-widgets = { path = "../canopy-widgets" }
clap.workspace = true
rand = "0.10.1"
unicode-width.workspace = true

[dev-dependencies]
canopy = { path = "../canopy", features = ["testing"] }
canopy-widgets = { path = "../canopy-widgets" }

[lints]
workspace = true
