[package]
name = "canopy-derive"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[lib]
proc-macro = true
doctest = false

[dependencies]
syn = { version = "2.0.117", features = ["extra-traits", "full"] }
quote = "1.0.45"
proc-macro2 = "1.0.106"
convert_case.workspace = true

[dev-dependencies]
canopy = { path = "../canopy", features = ["testing"] }
pretty_assertions = "1.4.1"

[lints]
workspace = true
