// @generated by `ruskel-snapshot`; do not edit.
//
// Package: canopy-geom
// Publish: crates.io
// Workspace dependencies: none
// Workspace dependents: canopy

//! Geometry primitives used across canopy.
//!
//! Rectangles and line segments use half-open bounds: their near edge is
//! included and their far edge is excluded. A rectangle is empty when either
//! dimension is zero, contains no points, and never intersects another
//! rectangle. Empty rectangles retain an anchor: one is contained by another
//! rectangle when all of its (coincident) edges lie within the containing
//! rectangle's closed edge bounds.
//!
//! Unsigned coordinates and sizes use saturating arithmetic unless an
//! operation is explicitly fallible. Edge calculations widen before adding so
//! rectangles extending beyond `u32::MAX` retain their full mathematical
//! extent. Signed-to-unsigned conversions clamp to `0..=u32::MAX`.

use std::{
    fmt::{Debug, Display},
    hash::Hash,
};

/// Geometry error type.
#[derive(Clone, Debug, Display, Eq, PartialEq, std::error::Error)]
pub enum Error {
    /// A point cannot be represented in the destination coordinate type.
    #[error("point ({x}, {y}) is outside the destination coordinate range")]
    CoordinateOutOfRange {
        /// Rejected x coordinate.
        x: i64,
        /// Rejected y coordinate.
        y: i64,
    },
    /// A zero-length window cannot be projected into a track.
    #[error("window cannot be zero length")]
    ZeroLengthWindow,
    /// A window lies outside the view used to project it.
    #[error("view {view:?} does not contain window {window:?}")]
    WindowOutsideView {
        /// Window extent.
        window: LineSegment,
        /// Enclosing view extent.
        view: LineSegment,
    },
    /// A line extent lies outside the requested rectangle axis.
    #[error("extent {extent:?} lies outside rectangle {rect:?}")]
    ExtentOutsideRect {
        /// Rejected extent.
        extent: LineSegment,
        /// Rectangle used as the bound.
        rect: Rect,
    },
    /// A line offset lies outside a rectangle's height.
    #[error("line offset {offset} exceeds rectangle height {height}")]
    LineOffsetOutside {
        /// Requested line offset.
        offset: u32,
        /// Rectangle height.
        height: u32,
    },
}

/// A frame's border regions extracted from a rectangle.
///
/// This struct represents the decomposition of a rectangle into its border
/// regions: top, bottom, left, right, and corner rectangles. It's useful for
/// drawing box borders or frame decorations.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct FrameRects {
    /// The top of the frame, not including corners
    pub top: Rect,
    /// The bottom of the frame, not including corners
    pub bottom: Rect,
    /// The left of the frame, not including corners
    pub left: Rect,
    /// The right of the frame, not including corners
    pub right: Rect,
    /// The top left corner
    pub topleft: Rect,
    /// The top right corner
    pub topright: Rect,
    /// The bottom left corner
    pub bottomleft: Rect,
    /// The bottom right corner
    pub bottomright: Rect,
    /// The space inside the frame
    pub inner: Rect,
}

impl FrameRects {
    /// Construct a new frame. If the rect is too small to fit the specified
    /// frame, we return an all-zero FrameRects.
    pub fn new(rect: Rect, border: u32) -> Self;
}

/// A horizontal line, one character high - essentially a Rect with height 1.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Line {
    /// Top-left point for the line.
    pub tl: Point,
    /// Width in cells.
    pub w: u32,
}

impl Line {
    /// Return this line indented from its start, giving up the columns it
    /// skips.
    ///
    /// Moving a line's start without shrinking its width is the mistake this
    /// exists to prevent. A line that keeps its width runs past the extent it
    /// was cut from, and painting it writes over whatever lies beyond, such as
    /// the border it was meant to sit inside. Indenting holds the far edge
    /// still, and indenting past that edge leaves an empty line rather than
    /// wrapping around.
    #[must_use]
    pub fn indent(&self, columns: u32) -> Self;

    /// Construct a line from coordinates and width.
    pub fn new(x: u32, y: u32, w: u32) -> Self;

    /// Convert the line into a rectangle of height 1.
    pub fn rect(&self) -> Rect;
}

/// A half-open, directionless one-dimensional line segment.
#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub struct LineSegment {
    /// The offset of this extent.
    pub off: u32,
    /// The length of this extent.
    pub len: u32,
}

impl LineSegment {
    /// Does other lie completely within this extent.
    pub fn contains(&self, other: Self) -> bool;

    /// Split this extent into (pre, active, post) extents, based on the
    /// position of a window within a view. The main use for this function is
    /// computation of the active indicator size and position in a scrollbar.
    ///
    /// Both ends of the active extent round to the nearest cell, so its
    /// position is never more than half a cell from the true proportion and
    /// the thumb moves near the midpoint of a cell instead of sticking at its
    /// start. The active extent keeps at least one cell, so a thumb stays
    /// visible and grabbable in a long document, and a track is never
    /// overrun.
    pub fn split_active(&self, window: Self, view: Self) -> crate::Result<(Self, Self, Self)>;
}

/// A 2D point in integer cell coordinates.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Point {
    /// X coordinate.
    pub x: u32,
    /// Y coordinate.
    pub y: u32,
}

impl Point {
    /// Origin point.
    pub const ZERO: Self = _;
    /// Construct a point from its coordinates.
    pub const fn new(x: u32, y: u32) -> Self;

    /// Shift the point by an offset, avoiding under- or overflow.
    #[must_use]
    pub fn scroll(&self, x: i32, y: i32) -> Self;
}

impl From<(u32, u32)> for Point {}

impl TryFrom<PointI32> for Point {
    type Error = Error;
}

/// A signed 2D point in integer cell coordinates.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct PointI32 {
    /// X coordinate.
    pub x: i32,
    /// Y coordinate.
    pub y: i32,
}

impl PointI32 {
    /// Clamp widened coordinates to the signed point range.
    pub fn clamped_from_i64(x: i64, y: i64) -> Self;

    /// Return the nearest unsigned point, raising negative coordinates to zero.
    pub fn clamped_point(self) -> Point;

    /// Convert widened coordinates without losing out-of-range information.
    pub fn try_from_i64(x: i64, y: i64) -> Result<Self, Error>;
}

impl TryFrom<Point> for PointI32 {
    type Error = Error;
}

/// A half-open rectangle with an unsigned origin and size.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Rect {
    /// Top-left corner
    pub tl: Point,
    /// Width
    pub w: u32,
    /// Height
    pub h: u32,
}

impl Rect {
    /// Empty rectangle at the origin.
    pub const ZERO: Self = _;
    /// Does this half-open rectangle contain the point?
    pub fn contains_point(&self, p: Point) -> bool;

    /// Does this rectangle completely enclose the other's half-open bounds?
    ///
    /// Empty rectangles are treated as anchored bounds. They are contained
    /// when their coincident edges fall within this rectangle's closed edge
    /// bounds, including the far edge.
    pub fn contains_rect(&self, other: Self) -> bool;

    /// The horizontal extent of this rect.
    pub fn hextent(&self) -> LineSegment;

    /// Extract a horizontal section of this rect based on an extent.
    pub fn hslice(&self, e: LineSegment) -> crate::Result<Self>;

    /// Calculate the intersection of this rectangle and another.
    pub fn intersect(&self, other: Self) -> Option<Self>;

    /// Does this rect have a zero size?
    pub fn is_empty(&self) -> bool;

    /// Return a line with a given offset in the rectangle.
    ///
    /// This remains fallible because an empty rectangle has no valid line and
    /// silently moving an out-of-range render request would hide layout bugs.
    pub fn line(&self, off: u32) -> crate::Result<Line>;

    /// Construct a rectangle from coordinates and size.
    pub const fn new(x: u32, y: u32, w: u32, h: u32) -> Self;

    /// Return the `Size` of this rectangle, which has the same size as the
    /// `Rect` but no location.
    pub const fn size(&self) -> Size;

    /// The vertical extent of this rect.
    pub fn vextent(&self) -> LineSegment;

    /// Extract a slice of this rect based on a vertical extent.
    pub fn vslice(&self, e: LineSegment) -> crate::Result<Self>;
}

/// A half-open rectangle with a signed origin and unsigned size.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct RectI32 {
    /// Top-left corner.
    pub tl: PointI32,
    /// Width.
    pub w: u32,
    /// Height.
    pub h: u32,
}

impl RectI32 {
    /// Bottom edge of the rect.
    pub fn bottom(&self) -> i64;

    /// Center point as widened coordinates.
    ///
    /// The tuple preserves centers beyond `i32` when a large unsigned size
    /// extends from a signed origin.
    pub fn center(&self) -> (i64, i64);

    /// Intersect this signed rect with an unsigned rect in the same coordinate
    /// space.
    pub fn intersect_rect(&self, other: Rect) -> Option<Rect>;

    /// Does this rect have a zero size?
    pub fn is_empty(&self) -> bool;

    /// Left edge of the rect.
    pub fn left(&self) -> i64;

    /// Construct a rectangle from coordinates and size.
    pub fn new(x: i32, y: i32, w: u32, h: u32) -> Self;

    /// Return true if this rect overlaps another horizontally.
    pub fn overlaps_horizontal(&self, other: Self) -> bool;

    /// Return true if this rect overlaps another vertically.
    pub fn overlaps_vertical(&self, other: Self) -> bool;

    /// Right edge of the rect.
    pub fn right(&self) -> i64;

    /// Return the rectangle's dimensions without its origin.
    pub const fn size(&self) -> Size;

    /// Convert a screen point to local coordinates relative to this rect.
    /// If the point is to the left/top of the rect, the result clamps to 0.
    pub fn to_local_point(&self, p: Point) -> Point;

    /// Top edge of the rect.
    pub fn top(&self) -> i64;
}

/// Result type for geometry operations.
pub type Result<T> = Result<T, Error>;

/// Size with width and height.
#[derive(Clone, Copy, Debug, Default, Eq, Hash, PartialEq)]
pub struct Size {
    /// Width component.
    pub w: u32,
    /// Height component.
    pub h: u32,
}

impl Size {
    /// Zero size.
    pub const ZERO: Self = _;
    /// Create a new size with the given width and height.
    pub const fn new(w: u32, h: u32) -> Self;

    /// Return a `Rect` with the same dimensions as the `Size`, but a location
    /// at (0, 0).
    pub fn rect(&self) -> Rect;
}

impl From<(u32, u32)> for Size {}
