// @generated by `ruskel-snapshot`; do not edit.

#[expect(
    clippy::multiple_inherent_impl,
    reason = "AppFactory construction and evaluation live in their owning modules."
)]
pub mod canopy_mcp {
    //! MCP and smoke-test helpers for canopy applications.

    /// Shared application constructor with an explicit domain-state declaration.
    pub struct AppFactory {}

    /// Identity and domain reset behavior declared by an application factory.
    pub struct AppMetadata {
        /// Stable application name used by replay compatibility checks.
        pub app: String,
        /// Domain reset behavior, independent of UI reconstruction.
        pub reset: ResetPolicy,
    }

    #[serde(crate = "::tmcp::__private::serde")]
    #[schemars(crate = "::tmcp::__private::schemars")]
    /// Request payload for applying a named fixture to a live app.
    pub struct ApplyFixtureRequest {
        /// Registered fixture name.
        pub name: String,
    }

    /// Response returned after a fixture is applied to a live app.
    pub struct ApplyFixtureResponse {
        /// Name of the applied fixture.
        pub applied: String,
    }

    /// Compact command availability record returned by bootstrap.
    pub struct BootstrapCommand {
        /// Command name relative to its owner.
        pub name: String,
        /// Widget owner name, or empty for free commands.
        pub owner: String,
        /// Whether the command currently resolves.
        pub available: bool,
        /// Eligibility, when an owner resolves.
        pub status: Option<String>,
        /// User-facing reason for disabled eligibility.
        pub disabled_reason: Option<String>,
        /// Missing originating event or row context, separate from eligibility.
        pub missing_requirements: Vec<String>,
    }

    /// Compact script journal record returned by bootstrap.
    pub struct BootstrapJournalEntry {
        /// Monotonic journal id.
        pub id: u64,
        #[schemars(with = "String")]
        /// Script origin.
        pub origin: canopy::ScriptOrigin,
        /// Whether the evaluation completed successfully.
        pub ok: bool,
        /// Number of logs emitted by this evaluation.
        pub log_count: usize,
        /// Number of assertions emitted by this evaluation.
        pub assertion_count: usize,
        /// Wall-clock duration in milliseconds.
        pub duration_ms: u64,
    }

    #[serde(crate = "::tmcp::__private::serde")]
    #[schemars(crate = "::tmcp::__private::schemars")]
    /// Optional dimensions for bootstrap replay preflight.
    pub struct BootstrapRequest {
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Requested headless viewport, or a live viewport compatibility check.
        pub viewport: Option<crate::Viewport>,
    }

    /// Bootstrap payload for an agent entering a Canopy app.
    pub struct BootstrapResponse {
        /// Execution identity and domain reset behavior for this bootstrap
        /// instance.
        pub metadata: crate::ExecutionMetadata,
        /// Operating guide for the automation surface.
        pub guide: String,
        /// Compact discovery inventory for the generated API.
        pub api_sources: Vec<ruau_script_api::ScriptApiEntry>,
        /// Registered fixtures.
        pub fixtures: Vec<canopy::FixtureInfo>,
        /// Default top-level script target policy.
        pub default_target: String,
        /// Availability from the root used by top-level script evaluation.
        pub default_commands: Vec<BootstrapCommand>,
        /// Availability from the currently focused node.
        pub focus_commands: Vec<BootstrapCommand>,
        /// Recent script journal entries.
        pub journal: Vec<BootstrapJournalEntry>,
    }

    /// Errors returned by `canopy-mcp`.
    pub enum Error {
        #[error(transparent)]
        /// A canopy runtime error.
        Canopy(canopy::error::Error),
        #[error(transparent)]
        /// A canopy command conversion error.
        Command(canopy::commands::CommandError),
        #[error(transparent)]
        /// An I/O error.
        Io(io::Error),
        #[error(transparent)]
        /// An MCP transport or protocol error.
        Tmcp(tmcp::Error),
        #[error("app setup failed: {0}")]
        /// The application factory failed to build an app instance.
        App(Box<dyn Send + StdError + Sync>),
        #[error("UDS listener thread panicked")]
        /// The UDS listener thread panicked while shutting down.
        ListenerThreadPanicked,
        #[error("UDS listener failed to report readiness")]
        /// The UDS listener stopped before reporting startup readiness.
        ListenerReadinessClosed,
        #[error("no .luau scripts found under {0}")]
        /// A smoke suite did not resolve to any Luau scripts.
        NoScripts(std::path::PathBuf),
    }

    /// Owned execution metadata returned even when an evaluation fails.
    pub struct ExecutionMetadata {
        /// Stable application identity.
        pub app: String,
        /// UI lifetime used by this evaluation.
        pub execution: ExecutionMode,
        /// Opaque identity of the application session, not a durable node
        /// reference.
        pub session_id: String,
        /// Evaluated or requested viewport, absent when live metadata could not be
        /// observed.
        pub viewport: Option<Viewport>,
        /// Effective domain reset contract.
        pub reset: ResetPolicy,
        /// Generated API identity, absent only when preparation could not obtain
        /// it.
        pub api_digest: Option<String>,
    }

    #[serde(rename_all = "kebab-case")]
    /// Whether evaluation constructs a new UI or uses the running application.
    pub enum ExecutionMode {
        #[default]
        /// Each evaluation constructs a fresh application UI.
        FreshAppPerEval,
        /// Evaluations share one running application.
        LiveSession,
    }

    /// Launcher mode for a Canopy application.
    pub enum LaunchMode {
        /// Run the interactive terminal UI.
        Run {
            /// Optional live MCP Unix-domain socket path.
            mcp_socket: Option<std::path::PathBuf>,
        },
        /// Serve the headless MCP automation server over stdio.
        HeadlessMcp,
        /// Print the generated Luau API and exit.
        Api,
    }

    #[serde(rename_all = "snake_case")]
    /// Application-declared reset behavior for domain data.
    pub enum ResetPolicy {
        #[default]
        /// Domain state can persist outside the UI instance.
        External,
        /// An explicitly applied fixture resets the relevant domain state.
        Fixture,
        /// Each factory invocation owns independent domain state.
        Isolated,
    }

    /// Result type used by `canopy-mcp`.
    pub type Result<T> = std::result::Result<T, Error>;

    /// Error details included in a failed script evaluation.
    pub struct ScriptErrorInfo {
        #[serde(rename = "type")]
        /// Pipeline stage that failed.
        pub error_type: ScriptErrorType,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        /// Stable host error category such as `no_target` or `unknown_command`,
        /// when the failure carried structured fields.
        pub kind: Option<canopy::error::ScriptErrorKind>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        /// Command id when the error came from command dispatch.
        pub command: Option<String>,
        #[serde(default, skip_serializing_if = "Option::is_none")]
        /// Owner name when the error came from node-target resolution.
        pub owner: Option<String>,
        /// Human-readable error message.
        pub message: String,
    }

    #[serde(rename_all = "snake_case")]
    /// Pipeline stage that caused a script evaluation to fail.
    pub enum ScriptErrorType {
        /// Application construction or initial rendering failed.
        Build,
        /// Luau typechecking failed.
        Typecheck,
        /// Evaluation exceeded its cooperative timeout.
        Timeout,
        /// Evaluation failed while running.
        Runtime,
        /// Evaluation was explicitly cancelled.
        Cancelled,
        /// Request metadata or options were invalid.
        Invalid,
    }

    /// Structured response for the `script_eval` tool and smoke runner.
    pub struct ScriptEvalOutcome {
        /// Execution identity and domain reset behavior for this request.
        pub metadata: crate::ExecutionMetadata,
        /// Whether the script completed successfully.
        pub success: bool,
        /// Final task state for the evaluation.
        pub state: ScriptTaskState,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional JSON-serializable script return value.
        pub value: Option<serde_json::Value>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        /// Log lines emitted during evaluation.
        pub logs: Vec<String>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        /// Assertion outcomes recorded during evaluation.
        pub assertions: Vec<canopy::script::ScriptAssertion>,
        #[serde(default, skip_serializing_if = "Vec::is_empty")]
        /// Typecheck diagnostics captured before execution.
        pub diagnostics: Vec<canopy::script::ScriptCheckDiagnostic>,
        /// Timing information for the request.
        pub timing: ScriptTiming,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Error payload when evaluation fails.
        pub error: Option<ScriptErrorInfo>,
    }

    #[serde(crate = "::tmcp::__private::serde")]
    #[schemars(crate = "::tmcp::__private::schemars")]
    /// Request payload for the `script_eval` tool.
    pub struct ScriptEvalRequest {
        /// Luau source code to execute.
        pub script: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional named fixture applied before evaluation.
        pub fixture: Option<String>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional evaluation timeout in milliseconds.
        pub timeout_ms: Option<u64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        /// Optional headless dimensions; live requests may only confirm current
        /// dimensions.
        pub viewport: Option<crate::Viewport>,
    }

    /// Result of running one smoke script.
    pub struct ScriptOutcome {
        /// Script path on disk.
        pub path: std::path::PathBuf,
        /// Fixture derived for this script, if any.
        pub fixture: Option<String>,
        /// Structured script outcome, carrying success, timing, and error details.
        pub outcome: crate::script::ScriptEvalOutcome,
    }

    #[serde(rename_all = "snake_case")]
    /// Evaluation task state exposed to automation callers.
    pub enum ScriptTaskState {
        /// Evaluation completed successfully.
        Completed,
        /// Evaluation failed before completion.
        Failed,
        /// Evaluation stopped at the cooperative timeout boundary.
        TimedOut,
        /// Evaluation was explicitly cancelled.
        Cancelled,
    }

    /// Timing information for a script evaluation.
    pub struct ScriptTiming {
        /// Time spent constructing and rendering the headless app.
        pub build_ms: u64,
        /// Time spent executing the script and final render.
        pub exec_ms: u64,
        /// Total wall-clock time for the request.
        pub total_ms: u64,
    }

    /// Configuration for a smoke-suite run.
    pub struct SuiteConfig {
        /// Root directory to scan for `.luau` scripts when no explicit script list
        /// is provided.
        pub suite_dir: std::path::PathBuf,
        /// Optional subset of scripts to run. Relative paths are resolved against
        /// `suite_dir`.
        pub scripts: Vec<std::path::PathBuf>,
        /// Optional per-script timeout in milliseconds.
        pub timeout_ms: Option<u64>,
        /// Stop after the first failed script.
        pub fail_fast: bool,
    }

    /// Aggregated result for a smoke suite.
    pub struct SuiteOutcome {
        /// Per-script results in execution order.
        pub scripts: Vec<ScriptOutcome>,
    }

    /// Handle for a running live UDS MCP listener.
    pub struct UdsServerHandle {}

    /// Terminal dimensions in cells, serialized independently of internal geometry.
    pub struct Viewport {
        /// Number of columns.
        pub width: u32,
        /// Number of rows.
        pub height: u32,
    }

    /// Resolve the ordered list of smoke scripts for a suite run.
    ///
    /// An explicit script list keeps its given order, because that order decides
    /// which script a fail-fast run stops on. Discovered files are sorted so a
    /// directory walk is reproducible.
    pub fn discover_scripts(config: &SuiteConfig) -> crate::Result<Vec<std::path::PathBuf>> {}

    /// Derive a fixture name from the first path component under the suite root.
    ///
    /// Only a normal component names a fixture; a root, prefix, or `..` component
    /// does not.
    pub fn fixture_for_script(
        suite_dir: &std::path::Path,
        script: &std::path::Path,
    ) -> Option<String> {
    }

    /// Launch a Canopy app in the selected mode.
    ///
    /// The caller owns CLI parsing and app-specific configuration. This function
    /// owns the repeated framework wiring: API output, headless MCP, live MCP, and
    /// the terminal runloop.
    pub fn launch(
        factory: crate::AppFactory,
        mode: LaunchMode,
        run_options: canopy::terminal::RunOptions,
    ) -> crate::Result<i32> {
    }

    /// Run a smoke suite against fresh headless app instances.
    pub fn run_suite(
        factory: &crate::AppFactory,
        config: &SuiteConfig,
    ) -> crate::Result<SuiteOutcome> {
    }

    /// Serve `bootstrap`, `script_eval`, `script_api`, and `fixtures` over stdio
    /// for an app factory.
    /// This low-level entry point grants trusted-local access to all exposed native
    /// actions. Calling this function is the application's automation opt-in.
    pub fn serve_stdio(factory: crate::AppFactory) -> crate::Result<()> {}

    /// Serve live MCP automation for a running canopy app over a Unix-domain
    /// socket.
    /// This low-level entry point grants trusted-local access. The application must
    /// choose a private socket directory and enforce suitable host filesystem
    /// permissions.
    pub fn serve_uds(
        socket_path: impl AsRef<std::path::Path>,
        automation: canopy::AutomationHandle,
        metadata: crate::AppMetadata,
    ) -> crate::Result<UdsServerHandle> {
    }

    impl AppFactory {
        /// Build one fully configured application instance.
        pub fn build(&self) -> crate::Result<Canopy> {}

        /// Declare application metadata and the constructor for built instances.
        pub fn new<F>(metadata: AppMetadata, factory: F) -> Self
        where
            F: 'static + Fn() -> crate::Result<Canopy> + Send + Sync, {
        }

        /// Read the application declaration without constructing its UI.
        pub fn metadata(&self) -> &AppMetadata {}

        /// Bootstrap at requested dimensions, validated before factory invocation.
        pub fn bootstrap(&self, request: &BootstrapRequest) -> Result<BootstrapResponse> {}

        /// Evaluate a Luau script against a fresh headless app.
        pub fn evaluate(&self, request: &ScriptEvalRequest) -> ScriptEvalOutcome {}

        /// Render and return the app's Luau API definition.
        pub fn script_api(&self) -> Result<String> {}

        /// Return the evaluator's registered fixture catalog.
        pub fn fixtures(&self) -> Result<Vec<FixtureInfo>> {}
    }

    impl Clone for AppFactory {
        fn clone(&self) -> AppFactory {}
    }

    impl Clone for AppMetadata {
        fn clone(&self) -> AppMetadata {}
    }

    impl Debug for AppMetadata {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for AppMetadata {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for AppMetadata {
        fn eq(&self, other: &AppMetadata) -> bool {}
    }

    impl Clone for ApplyFixtureRequest {
        fn clone(&self) -> ApplyFixtureRequest {}
    }

    impl Debug for ApplyFixtureRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ApplyFixtureRequest {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ApplyFixtureRequest {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ApplyFixtureRequest {
        fn eq(&self, other: &ApplyFixtureRequest) -> bool {}
    }

    impl Serialize for ApplyFixtureRequest {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ApplyFixtureRequest {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ApplyFixtureResponse {
        fn clone(&self) -> ApplyFixtureResponse {}
    }

    impl Debug for ApplyFixtureResponse {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ApplyFixtureResponse {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ApplyFixtureResponse {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ApplyFixtureResponse {
        fn eq(&self, other: &ApplyFixtureResponse) -> bool {}
    }

    impl Serialize for ApplyFixtureResponse {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ApplyFixtureResponse {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for BootstrapCommand {
        fn clone(&self) -> BootstrapCommand {}
    }

    impl Debug for BootstrapCommand {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for BootstrapCommand {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for BootstrapCommand {
        fn eq(&self, other: &BootstrapCommand) -> bool {}
    }

    impl Serialize for BootstrapCommand {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for BootstrapCommand {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for BootstrapJournalEntry {
        fn clone(&self) -> BootstrapJournalEntry {}
    }

    impl Debug for BootstrapJournalEntry {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for BootstrapJournalEntry {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for BootstrapJournalEntry {
        fn eq(&self, other: &BootstrapJournalEntry) -> bool {}
    }

    impl Serialize for BootstrapJournalEntry {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for BootstrapJournalEntry {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for BootstrapRequest {
        fn clone(&self) -> BootstrapRequest {}
    }

    impl Debug for BootstrapRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for BootstrapRequest {
        fn default() -> BootstrapRequest {}
    }

    impl JsonSchema for BootstrapRequest {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for BootstrapRequest {
        fn eq(&self, other: &BootstrapRequest) -> bool {}
    }

    impl Serialize for BootstrapRequest {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for BootstrapRequest {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for BootstrapResponse {
        fn clone(&self) -> BootstrapResponse {}
    }

    impl Debug for BootstrapResponse {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for BootstrapResponse {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for BootstrapResponse {
        fn eq(&self, other: &BootstrapResponse) -> bool {}
    }

    impl Serialize for BootstrapResponse {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for BootstrapResponse {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ExecutionMetadata {
        fn clone(&self) -> ExecutionMetadata {}
    }

    impl Debug for ExecutionMetadata {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ExecutionMetadata {
        fn default() -> ExecutionMetadata {}
    }

    impl Eq for ExecutionMetadata {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ExecutionMetadata {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ExecutionMetadata {
        fn eq(&self, other: &ExecutionMetadata) -> bool {}
    }

    impl Serialize for ExecutionMetadata {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ExecutionMetadata {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ExecutionMode {
        fn clone(&self) -> ExecutionMode {}
    }

    impl Debug for ExecutionMode {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ExecutionMode {
        fn default() -> ExecutionMode {}
    }

    impl Eq for ExecutionMode {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ExecutionMode {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ExecutionMode {
        fn eq(&self, other: &ExecutionMode) -> bool {}
    }

    impl Serialize for ExecutionMode {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ExecutionMode {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ResetPolicy {
        fn clone(&self) -> ResetPolicy {}
    }

    impl Debug for ResetPolicy {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ResetPolicy {
        fn default() -> ResetPolicy {}
    }

    impl Eq for ResetPolicy {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ResetPolicy {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ResetPolicy {
        fn eq(&self, other: &ResetPolicy) -> bool {}
    }

    impl Serialize for ResetPolicy {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ResetPolicy {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptErrorInfo {
        fn clone(&self) -> ScriptErrorInfo {}
    }

    impl Debug for ScriptErrorInfo {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for ScriptErrorInfo {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptErrorInfo {
        fn eq(&self, other: &ScriptErrorInfo) -> bool {}
    }

    impl Serialize for ScriptErrorInfo {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptErrorInfo {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptErrorType {
        fn clone(&self) -> ScriptErrorType {}
    }

    impl Debug for ScriptErrorType {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptErrorType {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl From<ScriptErrorType> for ScriptTaskState {
        fn from(error_type: ScriptErrorType) -> Self {}
    }

    impl JsonSchema for ScriptErrorType {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptErrorType {
        fn eq(&self, other: &ScriptErrorType) -> bool {}
    }

    impl Serialize for ScriptErrorType {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptErrorType {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptEvalOutcome {
        fn clone(&self) -> ScriptEvalOutcome {}
    }

    impl Debug for ScriptEvalOutcome {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for ScriptEvalOutcome {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptEvalOutcome {
        fn eq(&self, other: &ScriptEvalOutcome) -> bool {}
    }

    impl ScriptEvalOutcome {
        /// Encode the outcome as an MCP tool result.
        pub fn to_tool_result(&self) -> CallToolResult {}
    }

    impl Serialize for ScriptEvalOutcome {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptEvalOutcome {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptEvalRequest {
        fn clone(&self) -> ScriptEvalRequest {}
    }

    impl Debug for ScriptEvalRequest {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl JsonSchema for ScriptEvalRequest {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptEvalRequest {
        fn eq(&self, other: &ScriptEvalRequest) -> bool {}
    }

    impl ScriptEvalRequest {
        /// Construct a request with default fixture, timeout, and viewport options.
        pub fn new(script: impl Into<String>) -> Self {}
    }

    impl Serialize for ScriptEvalRequest {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptEvalRequest {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptOutcome {
        fn clone(&self) -> ScriptOutcome {}
    }

    impl Debug for ScriptOutcome {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for ScriptOutcome {
        fn eq(&self, other: &ScriptOutcome) -> bool {}
    }

    impl Clone for ScriptTaskState {
        fn clone(&self) -> ScriptTaskState {}
    }

    impl Debug for ScriptTaskState {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for ScriptTaskState {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl From<ScriptErrorType> for ScriptTaskState {
        fn from(error_type: ScriptErrorType) -> Self {}
    }

    impl JsonSchema for ScriptTaskState {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptTaskState {
        fn eq(&self, other: &ScriptTaskState) -> bool {}
    }

    impl Serialize for ScriptTaskState {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptTaskState {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for ScriptTiming {
        fn clone(&self) -> ScriptTiming {}
    }

    impl Debug for ScriptTiming {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ScriptTiming {
        fn default() -> ScriptTiming {}
    }

    impl Eq for ScriptTiming {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl JsonSchema for ScriptTiming {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for ScriptTiming {
        fn eq(&self, other: &ScriptTiming) -> bool {}
    }

    impl Serialize for ScriptTiming {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl<'de> Deserialize<'de> for ScriptTiming {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Clone for SuiteConfig {
        fn clone(&self) -> SuiteConfig {}
    }

    impl Debug for SuiteConfig {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for SuiteConfig {
        fn eq(&self, other: &SuiteConfig) -> bool {}
    }

    impl SuiteConfig {
        /// Construct a config using a suite directory and default options.
        pub fn new(suite_dir: impl Into<PathBuf>) -> Self {}
    }

    impl Clone for SuiteOutcome {
        fn clone(&self) -> SuiteOutcome {}
    }

    impl Debug for SuiteOutcome {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl PartialEq for SuiteOutcome {
        fn eq(&self, other: &SuiteOutcome) -> bool {}
    }

    impl SuiteOutcome {
        /// Return true when all smoke scripts passed.
        pub fn success(&self) -> bool {}
    }

    impl Clone for Viewport {
        fn clone(&self) -> Viewport {}
    }

    impl Debug for Viewport {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Viewport {
        fn default() -> Self {}
    }

    impl Eq for Viewport {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl From<Size> for Viewport {
        fn from(size: Size) -> Self {}
    }

    impl From<Viewport> for canopy::geom::Size {
        fn from(viewport: Viewport) -> Self {}
    }

    impl JsonSchema for Viewport {
        fn inline_schema() -> bool {}

        fn json_schema(generator: &mut schemars::SchemaGenerator) -> schemars::Schema {}

        fn schema_id() -> schemars::_private::alloc::borrow::Cow<'static, str> {}

        fn schema_name() -> schemars::_private::alloc::borrow::Cow<'static, str> {}
    }

    impl PartialEq for Viewport {
        fn eq(&self, other: &Viewport) -> bool {}
    }

    impl Serialize for Viewport {
        fn serialize<__S>(
            &self,
            __serializer: __S,
        ) -> _serde::__private228::Result<__S::Ok, __S::Error>
        where
            __S: _serde::Serializer, {
        }
    }

    impl Viewport {
        /// Reject empty or excessive headless dimensions before constructing an
        /// app.
        pub fn validate(self) -> crate::Result<()> {}
    }

    impl<'de> Deserialize<'de> for Viewport {
        fn deserialize<__D>(__deserializer: __D) -> _serde::__private228::Result<Self, __D::Error>
        where
            __D: _serde::Deserializer<'de>, {
        }
    }

    impl Debug for Error {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for Error {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Error for Error {
        fn source(
            &self,
        ) -> ::core::option::Option<&(dyn ::thiserror::__private18::Error + 'static)> {
        }
    }

    impl Error {
        /// Wrap an application-specific setup error.
        pub fn app(error: impl Into<Box<dyn Send + StdError + Sync>>) -> Self {}
    }

    impl From<CommandError> for Error {
        fn from(source: CommandError) -> Self {}
    }

    impl From<Error> for Error {
        fn from(source: CanopyError) -> Self {}
    }

    impl From<Error> for Error {
        fn from(source: io::Error) -> Self {}
    }

    impl From<Error> for Error {
        fn from(source: tmcp::Error) -> Self {}
    }

    impl Drop for UdsServerHandle {
        fn drop(&mut self) {}
    }

    impl UdsServerHandle {
        /// Stop the listener and remove the socket path.
        pub fn stop(self) -> Result<()> {}
    }
}
