// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_examples {
    //! Example widgets used by canopy demos.

    pub mod chargym {
        //! Char gym example nodes.
        //! Chargym: A Unicode width and wide character demo.

        /// Root node for the chargym demo.
        #[derive(Default)]
        pub struct CharGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CharGym {
            /// Construct a new chargym demo.
            pub fn new() -> Self {}
        }

        impl Register for CharGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for CharGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod editorgym {
        //! Editor gym example nodes.

        /// Root widget for the editor gym demo.
        #[derive(Default)]
        pub struct EditorGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for EditorGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl EditorGym {
            /// Construct a new editor gym demo.
            pub fn new() -> Self {}
        }

        impl Register for EditorGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for EditorGym {
            fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod focusgym {
        //! Focus gym example nodes.

        /// Root node for the focus gym demo.
        #[derive(Default)]
        pub struct FocusGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for FocusGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl FocusGym {
            /// Construct a new focus gym.
            pub fn new() -> Self {}
        }

        impl Register for FocusGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for FocusGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod fontgym {
        //! Font gym example nodes.

        /// Demo node that renders ASCII font banners.
        #[derive(Default)]
        pub struct FontGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl FontGym {
            /// Construct a new font gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for FontGym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Result<Option<Duration>> {}
        }
    }

    pub mod framegym {
        //! Frame gym example nodes.

        /// Root node for the frame gym demo.
        #[derive(Default)]
        pub struct FrameGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl FrameGym {
            /// Construct a new frame gym.
            pub fn new() -> Self {}
        }

        impl Register for FrameGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for FrameGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod imgview {
        //! Image viewer example nodes.

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}
    }

    pub mod intervals {
        //! Intervals example nodes.

        /// Root node for the intervals demo.
        #[derive(Default)]
        pub struct Intervals;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for Intervals {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Intervals {
            /// Construct a new intervals demo.
            pub fn new() -> Self {}
        }

        impl Register for Intervals {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for Intervals {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, c: &mut dyn Context) -> Result<Option<Duration>> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod listgym {
        //! List gym example nodes.

        /// Root node for the list gym demo.
        #[derive(Default)]
        pub struct ListGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for ListGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl ListGym {
            /// Construct a new list gym demo.
            pub fn new() -> Self {}
        }

        impl Register for ListGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for ListGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod pager {
        //! Pager example nodes.

        /// Simple pager widget for file contents.
        pub struct Pager {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl Pager {
            /// Construct a pager with initial contents.
            pub fn new(contents: &str) -> Self {}
        }

        impl Register for Pager {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for Pager {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod stylegym {
        //! Stylegym example nodes.
        //! Stylegym: a viewer for Canopy themes and styles.
        //!
        //! A sidebar titled Styles picks the theme and the effects. The untitled main
        //! pane shows the theme through tabbed pages: resolved palette swatches, every
        //! rule in the theme, stock widgets, syntax highlighting, and text samples. A
        //! modal overlay shows how the pane dims.

        /// Root widget for the stylegym demo.
        #[derive(Default)]
        pub struct Stylegym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for Stylegym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Register for Stylegym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Stylegym {
            /// Create a new stylegym instance.
            pub fn new() -> Self {}
        }

        impl Widget for Stylegym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod termgym {
        //! Terminal gym example nodes.

        /// Multi-terminal demo widget.
        #[derive(Default)]
        pub struct TermGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for TermGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Register for TermGym {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl TermGym {
            /// Construct the terminal gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for TermGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod textgym {
        //! Text gym example nodes.

        /// Demo node that displays multiple text variants.
        #[derive(Default)]
        pub struct TextGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl TextGym {
            /// Construct a new text gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for TextGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod widget {
        //! Widget demo nodes.
        //! Widget demo entry points.

        /// Host widget that centers a padded child within optional sizing overrides.
        pub struct DemoHost {}

        /// Common sizing configuration for widget demos.
        #[derive(Clone, Copy, Debug, Default)]
        pub struct DemoSize {
            /// Optional fixed width override.
            pub width: Option<u32>,
            /// Optional fixed height override.
            pub height: Option<u32>,
        }

        /// Font widget configuration.
        pub struct FontDemo {}

        /// Font source data for demo cycling.
        #[derive(Clone, Debug)]
        pub struct FontSource {}

        /// List widget configuration.
        pub struct ListDemo {}

        /// Terminal demo widget with three commands.
        #[derive(Default)]
        pub struct TermDemo {}

        impl CommandNode for TermDemo {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl TermDemo {
            /// Construct a terminal demo.
            pub fn new() -> Self {}
        }

        impl Widget for TermDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, rndr: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl DemoHost {
            #[must_use]
            /// Set the inner padding for the demo host.
            pub fn with_inner_padding(self, padding: u32) -> Self {}

            #[must_use]
            /// Set the outer padding for the demo host.
            pub fn with_outer_padding(self, padding: u32) -> Self {}

            /// Build a demo host for the provided widget.
            pub fn new(child: impl Into<Box<dyn Widget>>, size: DemoSize, frame: bool) -> Self {}
        }

        impl Widget for DemoHost {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}
        }

        impl DemoSize {
            /// Create sizing overrides.
            pub fn new(width: Option<u32>, height: Option<u32>) -> Self {}
        }

        impl FontDemo {
            /// Build a font demo widget.
            pub fn new(
                text: impl Into<String>,
                fonts: Vec<FontSource>,
                interval: Duration,
                exit_after_cycle: bool,
                effects: FontEffects,
            ) -> Self {
            }
        }

        impl Widget for FontDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Result<Option<Duration>> {}
        }

        impl FontSource {
            /// Build a font source from raw bytes.
            pub fn new(label: impl Into<String>, bytes: Vec<u8>) -> Self {}
        }

        impl ListDemo {
            /// Build a list demo widget.
            pub fn new(interval: Duration) -> Self {}

            /// Return the width and height that exactly fit the demo's items.
            pub fn natural_size() -> (u32, u32) {}
        }

        impl Widget for ListDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Result<Option<Duration>> {}
        }
    }

    pub mod widget_editor {
        //! Widget editor example nodes.

        /// Widget editor example that opens a Rust file with syntax highlighting.
        pub struct WidgetEditor {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Return a lowercase file extension hint for syntax selection.
        pub fn file_extension(path: &std::path::Path) -> String {}

        /// Return a short title for the editor frame.
        pub fn file_title(path: &std::path::Path) -> String {}

        impl Register for WidgetEditor {
            fn register(setup: &mut Setup) -> Result<()> {}
        }

        impl Widget for WidgetEditor {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }

        impl WidgetEditor {
            /// Construct a widget editor from file contents and metadata.
            pub fn new(
                contents: impl Into<String>,
                extension: impl Into<String>,
                title: impl Into<String>,
            ) -> Self {
            }
        }
    }

    #[must_use]
    /// Start demo registration with Root and its first-preparation help setup.
    pub fn demo_canopy() -> canopy::CanopyBuilder {}

    /// Install one demo app under a root and run the terminal loop.
    pub fn run_demo<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
    ) -> canopy::error::Result<i32> {
    }

    /// Install a demo and run it with explicit terminal interrupt behavior.
    pub fn run_demo_with_options<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
        options: canopy::terminal::RunOptions,
    ) -> canopy::error::Result<i32> {
    }
}
