// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_geom {
    //! Geometry primitives used across canopy.
    //!
    //! Rectangles and line segments use half-open bounds: their near edge is
    //! included and their far edge is excluded. A rectangle is empty when either
    //! dimension is zero, contains no points, and never intersects another
    //! rectangle. Empty rectangles retain an anchor: one is contained by another
    //! rectangle when all of its (coincident) edges lie within the containing
    //! rectangle's closed edge bounds.
    //!
    //! Unsigned coordinates and sizes use saturating arithmetic unless an
    //! operation is explicitly fallible. Edge calculations widen before adding so
    //! rectangles extending beyond `u32::MAX` retain their full mathematical
    //! extent. Signed-to-unsigned conversions clamp to `0..=u32::MAX`.

    /// Geometry error type.
    pub enum Error {
        #[error("point ({x}, {y}) is outside the destination coordinate range")]
        /// A point cannot be represented in the destination coordinate type.
        CoordinateOutOfRange {
            /// Rejected x coordinate.
            x: i64,
            /// Rejected y coordinate.
            y: i64,
        },
        #[error("window cannot be zero length")]
        /// A zero-length window cannot be projected into a track.
        ZeroLengthWindow,
        #[error("view {view:?} does not contain window {window:?}")]
        /// A window lies outside the view used to project it.
        WindowOutsideView {
            /// Window extent.
            window: crate::LineSegment,
            /// Enclosing view extent.
            view: crate::LineSegment,
        },
        #[error("extent {extent:?} lies outside rectangle {rect:?}")]
        /// A line extent lies outside the requested rectangle axis.
        ExtentOutsideRect {
            /// Rejected extent.
            extent: crate::LineSegment,
            /// Rectangle used as the bound.
            rect: crate::Rect,
        },
        #[error("line offset {offset} exceeds rectangle height {height}")]
        /// A line offset lies outside a rectangle's height.
        LineOffsetOutside {
            /// Requested line offset.
            offset: u32,
            /// Rectangle height.
            height: u32,
        },
    }

    /// A frame's border regions extracted from a rectangle.
    ///
    /// This struct represents the decomposition of a rectangle into its border
    /// regions: top, bottom, left, right, and corner rectangles. It's useful for
    /// drawing box borders or frame decorations.
    pub struct FrameRects {
        /// The top of the frame, not including corners
        pub top: super::Rect,
        /// The bottom of the frame, not including corners
        pub bottom: super::Rect,
        /// The left of the frame, not including corners
        pub left: super::Rect,
        /// The right of the frame, not including corners
        pub right: super::Rect,
        /// The top left corner
        pub topleft: super::Rect,
        /// The top right corner
        pub topright: super::Rect,
        /// The bottom left corner
        pub bottomleft: super::Rect,
        /// The bottom right corner
        pub bottomright: super::Rect,
        /// The space inside the frame
        pub inner: super::Rect,
    }

    /// A horizontal line, one character high - essentially a Rect with height 1.
    pub struct Line {
        /// Top-left point for the line.
        pub tl: super::Point,
        /// Width in cells.
        pub w: u32,
    }

    /// A half-open, directionless one-dimensional line segment.
    pub struct LineSegment {
        /// The offset of this extent.
        pub off: u32,
        /// The length of this extent.
        pub len: u32,
    }

    /// A 2D point in integer cell coordinates.
    pub struct Point {
        /// X coordinate.
        pub x: u32,
        /// Y coordinate.
        pub y: u32,
    }

    /// A signed 2D point in integer cell coordinates.
    pub struct PointI32 {
        /// X coordinate.
        pub x: i32,
        /// Y coordinate.
        pub y: i32,
    }

    /// A half-open rectangle with an unsigned origin and size.
    pub struct Rect {
        /// Top-left corner
        pub tl: super::Point,
        /// Width
        pub w: u32,
        /// Height
        pub h: u32,
    }

    /// A half-open rectangle with a signed origin and unsigned size.
    pub struct RectI32 {
        /// Top-left corner.
        pub tl: super::PointI32,
        /// Width.
        pub w: u32,
        /// Height.
        pub h: u32,
    }

    /// Result type for geometry operations.
    pub type Result<T> = std::result::Result<T, Error>;

    /// Size with width and height.
    pub struct Size {
        /// Width component.
        pub w: u32,
        /// Height component.
        pub h: u32,
    }

    impl Clone for Error {
        fn clone(&self) -> Error {}
    }

    impl Debug for Error {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Display for Error {
        fn fmt(&self, __formatter: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {}
    }

    impl Eq for Error {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for Error {
        fn eq(&self, other: &Error) -> bool {}
    }

    impl Clone for FrameRects {
        fn clone(&self) -> FrameRects {}
    }

    impl Debug for FrameRects {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for FrameRects {
        fn default() -> FrameRects {}
    }

    impl Eq for FrameRects {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl FrameRects {
        /// Construct a new frame. If the rect is too small to fit the specified
        /// frame, we return an all-zero FrameRects.
        pub fn new(rect: Rect, border: u32) -> Self {}
    }

    impl Hash for FrameRects {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for FrameRects {
        fn eq(&self, other: &FrameRects) -> bool {}
    }

    impl Clone for Line {
        fn clone(&self) -> Line {}
    }

    impl Debug for Line {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Line {
        fn default() -> Line {}
    }

    impl Eq for Line {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for Line {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl Line {
        /// Construct a line from coordinates and width.
        pub fn new(x: u32, y: u32, w: u32) -> Self {}

        /// Convert the line into a rectangle of height 1.
        pub fn rect(&self) -> Rect {}
    }

    impl PartialEq for Line {
        fn eq(&self, other: &Line) -> bool {}
    }

    impl Clone for LineSegment {
        fn clone(&self) -> LineSegment {}
    }

    impl Debug for LineSegment {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for LineSegment {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for LineSegment {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl LineSegment {
        /// Does other lie completely within this extent.
        pub fn contains(&self, other: Self) -> bool {}

        /// Split this extent into (pre, active, post) extents, based on the
        /// position of a window within a view. The main use for this function is
        /// computation of the active indicator size and position in a scrollbar.
        pub fn split_active(&self, window: Self, view: Self) -> Result<(Self, Self, Self)> {}
    }

    impl PartialEq for LineSegment {
        fn eq(&self, other: &LineSegment) -> bool {}
    }

    impl Clone for Point {
        fn clone(&self) -> Point {}
    }

    impl Debug for Point {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Point {
        fn default() -> Point {}
    }

    impl Eq for Point {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl From<(u32, u32)> for Point {
        fn from(v: (u32, u32)) -> Self {}
    }

    impl Hash for Point {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for Point {
        fn eq(&self, other: &Point) -> bool {}
    }

    impl Point {
        /// Construct a point from its coordinates.
        pub const fn new(x: u32, y: u32) -> Self {}

        /// Origin point.
        pub const ZERO: Self = _;
        /// Shift the point by an offset, avoiding under- or overflow.
        pub fn scroll(&self, x: i32, y: i32) -> Self {}
    }

    impl TryFrom<Point> for PointI32 {
        fn try_from(point: Point) -> Result<Self, Self::Error> {}

        type Error = Error;
    }

    impl TryFrom<PointI32> for crate::Point {
        fn try_from(point: PointI32) -> Result<Self, Self::Error> {}

        type Error = Error;
    }

    impl Clone for PointI32 {
        fn clone(&self) -> PointI32 {}
    }

    impl Debug for PointI32 {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for PointI32 {
        fn default() -> PointI32 {}
    }

    impl Eq for PointI32 {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for PointI32 {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for PointI32 {
        fn eq(&self, other: &PointI32) -> bool {}
    }

    impl PointI32 {
        /// Clamp widened coordinates to the signed point range.
        pub fn clamped_from_i64(x: i64, y: i64) -> Self {}

        /// Convert widened coordinates without losing out-of-range information.
        pub fn try_from_i64(x: i64, y: i64) -> Result<Self, Error> {}
    }

    impl TryFrom<Point> for PointI32 {
        fn try_from(point: Point) -> Result<Self, Self::Error> {}

        type Error = Error;
    }

    impl TryFrom<PointI32> for crate::Point {
        fn try_from(point: PointI32) -> Result<Self, Self::Error> {}

        type Error = Error;
    }

    impl Clone for Rect {
        fn clone(&self) -> Rect {}
    }

    impl Debug for Rect {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Rect {
        fn default() -> Rect {}
    }

    impl Eq for Rect {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for Rect {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for Rect {
        fn eq(&self, other: &Rect) -> bool {}
    }

    impl Rect {
        /// Calculate the intersection of this rectangle and another.
        pub fn intersect(&self, other: Self) -> Option<Self> {}

        /// Construct a rectangle from coordinates and size.
        pub const fn new(x: u32, y: u32, w: u32, h: u32) -> Self {}

        /// Does this half-open rectangle contain the point?
        pub fn contains_point(&self, p: Point) -> bool {}

        /// Does this rect have a zero size?
        pub fn is_empty(&self) -> bool {}

        /// Does this rectangle completely enclose the other's half-open bounds?
        ///
        /// Empty rectangles are treated as anchored bounds. They are contained
        /// when their coincident edges fall within this rectangle's closed edge
        /// bounds, including the far edge.
        pub fn contains_rect(&self, other: Self) -> bool {}

        /// Empty rectangle at the origin.
        pub const ZERO: Self = _;
        /// Extract a horizontal section of this rect based on an extent.
        pub fn hslice(&self, e: LineSegment) -> Result<Self> {}

        /// Extract a slice of this rect based on a vertical extent.
        pub fn vslice(&self, e: LineSegment) -> Result<Self> {}

        /// Return a line with a given offset in the rectangle.
        ///
        /// This remains fallible because an empty rectangle has no valid line and
        /// silently moving an out-of-range render request would hide layout bugs.
        pub fn line(&self, off: u32) -> Result<Line> {}

        /// Return the `Size` of this rectangle, which has the same size as the
        /// `Rect` but no location.
        pub const fn size(&self) -> Size {}

        /// The horizontal extent of this rect.
        pub fn hextent(&self) -> LineSegment {}

        /// The vertical extent of this rect.
        pub fn vextent(&self) -> LineSegment {}
    }

    impl Clone for RectI32 {
        fn clone(&self) -> RectI32 {}
    }

    impl Debug for RectI32 {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for RectI32 {
        fn default() -> RectI32 {}
    }

    impl Eq for RectI32 {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for RectI32 {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for RectI32 {
        fn eq(&self, other: &RectI32) -> bool {}
    }

    impl RectI32 {
        /// Bottom edge of the rect.
        pub fn bottom(&self) -> i64 {}

        /// Center point as widened coordinates.
        ///
        /// The tuple preserves centers beyond `i32` when a large unsigned size
        /// extends from a signed origin.
        pub fn center(&self) -> (i64, i64) {}

        /// Construct a rectangle from coordinates and size.
        pub fn new(x: i32, y: i32, w: u32, h: u32) -> Self {}

        /// Convert a screen point to local coordinates relative to this rect.
        /// If the point is to the left/top of the rect, the result clamps to 0.
        pub fn to_local_point(&self, p: Point) -> Point {}

        /// Does this rect have a zero size?
        pub fn is_empty(&self) -> bool {}

        /// Intersect this signed rect with an unsigned rect in the same coordinate
        /// space.
        pub fn intersect_rect(&self, other: Rect) -> Option<Rect> {}

        /// Left edge of the rect.
        pub fn left(&self) -> i64 {}

        /// Return the rectangle's dimensions without its origin.
        pub const fn size(&self) -> Size {}

        /// Return true if this rect overlaps another horizontally.
        pub fn overlaps_horizontal(&self, other: Self) -> bool {}

        /// Return true if this rect overlaps another vertically.
        pub fn overlaps_vertical(&self, other: Self) -> bool {}

        /// Right edge of the rect.
        pub fn right(&self) -> i64 {}

        /// Top edge of the rect.
        pub fn top(&self) -> i64 {}
    }

    impl Clone for Size {
        fn clone(&self) -> Size {}
    }

    impl Debug for Size {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for Size {
        fn default() -> Size {}
    }

    impl Eq for Size {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl From<(u32, u32)> for Size {
        fn from(v: (u32, u32)) -> Self {}
    }

    impl Hash for Size {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for Size {
        fn eq(&self, other: &Size) -> bool {}
    }

    impl Size {
        /// Create a new size with the given width and height.
        pub const fn new(w: u32, h: u32) -> Self {}

        /// Return a `Rect` with the same dimensions as the `Size`, but a location
        /// at (0, 0).
        pub fn rect(&self) -> Rect {}

        /// Zero size.
        pub const ZERO: Self = _;
    }
}
