// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_examples {
    //! Example widgets used by canopy demos.

    pub mod chargym {
        //! Char gym example nodes.
        //! Chargym: A Unicode width and wide character demo.

        /// Root node for the chargym demo.
        pub struct CharGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CharGym {
            /// Construct a new chargym demo.
            pub fn new() -> Self {}
        }

        impl Default for CharGym {
            fn default() -> Self {}
        }

        impl Loader for CharGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for CharGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod editorgym {
        //! Editor gym example nodes.

        /// Root widget for the editor gym demo.
        pub struct EditorGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for EditorGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for EditorGym {
            fn default() -> Self {}
        }

        impl EditorGym {
            /// Construct a new editor gym demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll(dir: FocusDirection) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll_to(x: u32, y: u32) -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll_to() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for EditorGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for EditorGym {
            fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod focusgym {
        //! Focus gym example nodes.

        /// Root node for the focus gym demo.
        pub struct FocusGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for FocusGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for FocusGym {
            fn default() -> FocusGym {}
        }

        impl FocusGym {
            /// Construct a new focus gym.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_focused() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_focused() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for FocusGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for FocusGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod fontgym {
        //! Font gym example nodes.

        /// Demo node that renders ASCII font banners.
        pub struct FontGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl Default for FontGym {
            fn default() -> Self {}
        }

        impl FontGym {
            /// Construct a new font gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for FontGym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }
    }

    pub mod framegym {
        //! Frame gym example nodes.

        /// Root node for the frame gym demo.
        pub struct FrameGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl Default for FrameGym {
            fn default() -> Self {}
        }

        impl FrameGym {
            /// Construct a new frame gym.
            pub fn new() -> Self {}
        }

        impl Loader for FrameGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for FrameGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod imgview {
        //! Image viewer example nodes.

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}
    }

    pub mod intervals {
        //! Intervals example nodes.

        /// Root node for the intervals demo.
        pub struct Intervals;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for Intervals {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for Intervals {
            fn default() -> Self {}
        }

        impl Intervals {
            /// Construct a new intervals demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_item() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_item() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for Intervals {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for Intervals {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, c: &mut dyn Context) -> Option<Duration> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod listgym {
        //! List gym example nodes.

        /// Root node for the list gym demo.
        pub struct ListGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for ListGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for ListGym {
            fn default() -> Self {}
        }

        impl ListGym {
            /// Construct a new list gym demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_column() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_item() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_append_item() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_clear() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_column() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_column() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_item() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_append_item() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_column() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for ListGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for ListGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod pager {
        //! Pager example nodes.

        /// Simple pager widget for file contents.
        pub struct Pager {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl Loader for Pager {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Pager {
            /// Construct a pager with initial contents.
            pub fn new(contents: &str) -> Self {}
        }

        impl Widget for Pager {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod stylegym {
        //! Stylegym example nodes.
        //! Stylegym: A demonstration app for Canopy's styling features.
        //!
        //! This example showcases themes, effects, and modal overlays in a two-pane
        //! layout.

        /// Root widget for the stylegym demo.
        pub struct Stylegym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for Stylegym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for Stylegym {
            fn default() -> Self {}
        }

        impl Loader for Stylegym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Stylegym {
            /// Create a new stylegym instance.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_apply_effects() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_apply_theme() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_hide_modal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_show_modal() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_apply_effects() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_apply_theme() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_hide_modal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_show_modal() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for Stylegym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod termgym {
        //! Terminal gym example nodes.

        /// Multi-terminal demo widget.
        pub struct TermGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl CommandNode for TermGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for TermGym {
            fn default() -> Self {}
        }

        impl Loader for TermGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl TermGym {
            /// Construct the terminal gym demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_activate_terminal(index: usize) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_focus_active_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_new_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_new_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_next_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_prev_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_toggle_terminal_focus() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_activate_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_focus_active_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_new_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_new_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_next_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_prev_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_toggle_terminal_focus() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for TermGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod textgym {
        //! Text gym example nodes.

        /// Demo node that displays multiple text variants.
        pub struct TextGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        impl Default for TextGym {
            fn default() -> Self {}
        }

        impl TextGym {
            /// Construct a new text gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for TextGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod widget {
        //! Widget demo nodes.
        //! Widget demo entry points.

        /// Host widget that centers a padded child within optional sizing overrides.
        pub struct DemoHost {}

        /// Common sizing configuration for widget demos.
        pub struct DemoSize {
            /// Optional fixed width override.
            pub width: Option<u32>,
            /// Optional fixed height override.
            pub height: Option<u32>,
        }

        /// Font widget configuration.
        pub struct FontDemo {}

        /// Font source data for demo cycling.
        pub struct FontSource {}

        /// List widget configuration.
        pub struct ListDemo {}

        /// Terminal demo widget with three commands.
        pub struct TermDemo {}

        impl Clone for DemoSize {
            fn clone(&self) -> DemoSize {}
        }

        impl Debug for DemoSize {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Default for DemoSize {
            fn default() -> DemoSize {}
        }

        impl DemoSize {
            /// Create sizing overrides.
            pub fn new(width: Option<u32>, height: Option<u32>) -> Self {}
        }

        impl Clone for FontSource {
            fn clone(&self) -> FontSource {}
        }

        impl Debug for FontSource {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl FontSource {
            /// Build a font source from raw bytes.
            pub fn new(label: impl Into<String>, bytes: Vec<u8>) -> Self {}
        }

        impl CommandNode for TermDemo {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for TermDemo {
            fn default() -> Self {}
        }

        impl TermDemo {
            /// Construct a terminal demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_next_tab() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_next_tab() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for TermDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, rndr: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl DemoHost {
            /// Build a demo host for the provided widget.
            pub fn new(child: impl Into<Box<dyn Widget>>, size: DemoSize, frame: bool) -> Self {}

            /// Set the inner padding for the demo host.
            pub fn with_inner_padding(self, padding: u32) -> Self {}

            /// Set the outer padding for the demo host.
            pub fn with_outer_padding(self, padding: u32) -> Self {}
        }

        impl Widget for DemoHost {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}
        }

        impl FontDemo {
            /// Build a font demo widget.
            pub fn new(
                text: impl Into<String>,
                fonts: Vec<FontSource>,
                interval: Duration,
                exit_after_cycle: bool,
                effects: FontEffects,
            ) -> Self {
            }
        }

        impl Widget for FontDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }

        impl ListDemo {
            /// Build a list demo widget.
            pub fn new(interval: Duration) -> Self {}

            /// Return the width and height that exactly fit the demo's items.
            pub fn natural_size() -> (u32, u32) {}
        }

        impl Widget for ListDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }
    }

    pub mod widget_editor {
        //! Widget editor example nodes.

        /// Widget editor example that opens a Rust file with syntax highlighting.
        pub struct WidgetEditor {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Return a lowercase file extension hint for syntax selection.
        pub fn file_extension(path: &std::path::Path) -> String {}

        /// Return a short title for the editor frame.
        pub fn file_title(path: &std::path::Path) -> String {}

        impl Loader for WidgetEditor {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for WidgetEditor {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }

        impl WidgetEditor {
            /// Construct a widget editor from file contents and metadata.
            pub fn new(
                contents: impl Into<String>,
                extension: impl Into<String>,
                title: impl Into<String>,
            ) -> Self {
            }
        }
    }

    #[must_use]
    /// Start demo registration with Root and its first-preparation help setup.
    pub fn demo_canopy() -> canopy::CanopyBuilder {}

    /// Return the Luau API definitions for a built demo app.
    pub fn print_luau_api(cnpy: &mut canopy::Canopy) -> canopy::error::Result<String> {}

    /// Install one demo app under a root and run the terminal loop.
    pub fn run_demo<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
    ) -> canopy::error::Result<i32> {
    }

    /// Install a demo and run it with explicit terminal interrupt behavior.
    pub fn run_demo_with_options<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
        options: canopy::terminal::RunOptions,
    ) -> canopy::error::Result<i32> {
    }
}
