// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_widgets {
    //! Built-in widgets for canopy applications.
    //!
    //! This crate provides a collection of reusable widgets for building terminal
    //! user interfaces with canopy.

    #[expect(
        clippy::multiple_inherent_impl,
        reason = "Editor methods are split by rendering, vi, and prompt concerns."
    )]
    pub mod editor {
        //! Editor widget and supporting types.

        pub mod highlight {
            //! Syntax highlighting helpers.

            /// A highlighted span for a single line.
            pub struct HighlightSpan {
                /// Character range covered by the span.
                pub range: std::ops::Range<usize>,
                /// Style to apply to the span.
                pub style: canopy::style::Style,
            }

            /// A basic syntect-backed highlighter.
            pub struct SyntectHighlighter {}

            /// Trait for providing syntax highlighting spans.
            pub trait Highlighter {
                /// Return highlight spans for a line of text.
                fn highlight_line(&self, line: usize, text: &str) -> Vec<HighlightSpan>;
            }

            impl Clone for HighlightSpan {
                fn clone(&self) -> HighlightSpan {}
            }

            impl Debug for HighlightSpan {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
            }

            impl Clone for SyntectHighlighter {
                fn clone(&self) -> SyntectHighlighter {}
            }

            impl Debug for SyntectHighlighter {
                fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
            }

            impl Highlighter for SyntectHighlighter {
                fn highlight_line(&self, _line: usize, text: &str) -> Vec<HighlightSpan> {}
            }

            impl SyntectHighlighter {
                /// Construct a new syntect highlighter for the provided extension.
                pub fn new(extension: impl Into<String>) -> Self {}
            }
        }

        /// Editing mode for the editor widget.
        pub enum EditMode {
            /// Text entry mode with direct insertion.
            Text,
            /// Vi-style modal editing.
            Vi,
        }

        /// Editor widget implementation.
        pub struct Editor {}

        /// Configuration for the editor widget.
        pub struct EditorConfig {
            /// Allow multi-line content.
            pub multiline: bool,
            /// Wrapping mode.
            pub wrap: WrapMode,
            /// Auto-grow height to fit contents.
            pub auto_grow: bool,
            /// Minimum height when auto-growing.
            pub min_height: u32,
            /// Maximum height when auto-growing.
            pub max_height: Option<u32>,
            /// Edit mode behavior.
            pub mode: EditMode,
            /// Whether the editor is read-only.
            pub read_only: bool,
            /// Line number rendering mode.
            pub line_numbers: LineNumbers,
            /// Tab stop width in columns.
            pub tab_stop: usize,
        }

        /// Line number rendering mode.
        pub enum LineNumbers {
            /// Do not render line numbers.
            None,
            /// Render absolute line numbers.
            Absolute,
            /// Render relative line numbers (current line stays absolute).
            Relative,
        }

        /// Wrapping behavior for the editor.
        pub enum WrapMode {
            /// No wrapping; horizontal scrolling is enabled.
            None,
            /// Soft wrapping at the view width.
            Soft,
        }

        impl Clone for EditMode {
            fn clone(&self) -> EditMode {}
        }

        impl Debug for EditMode {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for EditMode {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for EditMode {
            fn eq(&self, other: &EditMode) -> bool {}
        }

        impl Clone for EditorConfig {
            fn clone(&self) -> EditorConfig {}
        }

        impl Debug for EditorConfig {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Default for EditorConfig {
            fn default() -> Self {}
        }

        impl EditorConfig {
            /// Configure auto-grow behavior.
            pub fn with_auto_grow(self, auto_grow: bool) -> Self {}

            /// Configure line number rendering.
            pub fn with_line_numbers(self, line_numbers: LineNumbers) -> Self {}

            /// Configure multiline behavior.
            pub fn with_multiline(self, multiline: bool) -> Self {}

            /// Configure read-only behavior.
            pub fn with_read_only(self, read_only: bool) -> Self {}

            /// Configure the edit mode.
            pub fn with_mode(self, mode: EditMode) -> Self {}

            /// Configure the maximum height.
            pub fn with_max_height(self, max_height: Option<u32>) -> Self {}

            /// Configure the minimum height.
            pub fn with_min_height(self, min_height: u32) -> Self {}

            /// Configure the tab stop width.
            pub fn with_tab_stop(self, tab_stop: usize) -> Self {}

            /// Configure wrapping mode.
            pub fn with_wrap(self, wrap: WrapMode) -> Self {}

            /// Construct a default editor configuration.
            pub fn new() -> Self {}
        }

        impl Clone for LineNumbers {
            fn clone(&self) -> LineNumbers {}
        }

        impl Debug for LineNumbers {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for LineNumbers {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for LineNumbers {
            fn eq(&self, other: &LineNumbers) -> bool {}
        }

        impl Clone for WrapMode {
            fn clone(&self) -> WrapMode {}
        }

        impl Debug for WrapMode {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for WrapMode {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for WrapMode {
            fn eq(&self, other: &WrapMode) -> bool {}
        }

        impl CommandNode for Editor {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Widget for Editor {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}

            fn cursor(&self) -> Option<cursor::Cursor> {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl super::widget::Editor {
            /// Construct an editor with a configuration.
            pub fn with_config(text: impl Into<String>, config: EditorConfig) -> Self {}

            /// Install a syntax highlighter.
            pub fn set_highlighter(&mut self, highlighter: Option<Box<dyn Highlighter>>) {}

            /// Move the cursor.
            /// @param dir The direction to move the cursor.
            pub fn move_cursor(&mut self, ctx: &mut dyn Context, dir: FocusDirection) {}

            /// Redo the last undone edit.
            pub fn redo(&mut self, _ctx: &mut dyn Context) {}

            /// Replace the buffer contents.
            pub fn set_text(&mut self, text: impl Into<String>) {}

            /// Replace the editor configuration.
            pub fn set_config(&mut self, config: EditorConfig) {}

            /// Return the buffer contents.
            pub fn text(&self) -> String {}

            /// Return the current editor configuration.
            pub fn config(&self) -> &EditorConfig {}

            /// Undo the last edit.
            pub fn undo(&mut self, _ctx: &mut dyn Context) {}

            /// Build a positional call with typed user arguments.
            pub fn call_move_cursor(dir: FocusDirection) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_redo() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_undo() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_move_cursor() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_redo() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_undo() -> &'static canopy::commands::CommandSpec {}
        }
    }

    pub mod font {
        //! ASCII font rasterization helpers.

        /// Rasterized font data for terminal rendering.
        pub struct Font {}

        /// Render large ASCII-font text into a bounded region.
        pub struct FontBanner {}

        /// Rendering effects applied to font output.
        pub struct FontEffects {
            /// Thicken strokes by adding extra coverage.
            pub bold: bool,
            /// Slant glyphs to the right.
            pub italic: bool,
            /// Draw an underline through the glyphs.
            pub underline: bool,
            /// Reduce contrast by dimming coverage.
            pub dim: bool,
            /// Draw an overline through the glyphs.
            pub overline: bool,
            /// Draw a strike-through line through the glyphs.
            pub strike: bool,
        }

        /// Renderer that converts fonts into terminal text.
        pub struct FontRenderer {}

        /// Widget that renders an image into terminal cells.
        pub struct ImageView {}

        /// Alignment configuration for font layouts.
        pub struct LayoutOptions {
            /// Horizontal alignment within the target canvas.
            pub h_align: canopy::layout::Align,
            /// Vertical alignment within the target canvas.
            pub v_align: canopy::layout::Align,
        }

        impl Clone for Font {
            fn clone(&self) -> Font {}
        }

        impl Font {
            /// Load a font from in-memory bytes.
            pub fn from_bytes(data: impl AsRef<[u8]>) -> Result<Self> {}

            /// Return the font name, if provided in metadata.
            pub fn name(&self) -> Option<&str> {}
        }

        impl Clone for FontEffects {
            fn clone(&self) -> FontEffects {}
        }

        impl Debug for FontEffects {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Default for FontEffects {
            fn default() -> FontEffects {}
        }

        impl Eq for FontEffects {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for FontEffects {
            fn eq(&self, other: &FontEffects) -> bool {}
        }

        impl Clone for LayoutOptions {
            fn clone(&self) -> LayoutOptions {}
        }

        impl Debug for LayoutOptions {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Default for LayoutOptions {
            fn default() -> LayoutOptions {}
        }

        impl Eq for LayoutOptions {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for LayoutOptions {
            fn eq(&self, other: &LayoutOptions) -> bool {}
        }

        impl CommandNode for ImageView {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl ImageView {
            /// Create a new image view widget from a file path.
            pub fn from_path(path: impl AsRef<Path>) -> Result<Self> {}

            /// Create a new image view widget.
            pub fn new(image: &RgbaImage) -> Self {}

            /// Pan by one step in the specified direction.
            /// @param dir The pan direction.
            pub fn pan(&mut self, ctx: &mut dyn Context, dir: FocusDirection) -> Result<()> {}

            /// Zoom around the view center.
            /// @param dir The zoom direction.
            pub fn zoom(&mut self, ctx: &mut dyn Context, dir: ZoomDirection) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_pan(dir: FocusDirection) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_zoom(dir: ZoomDirection) -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_pan() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_zoom() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for ImageView {
            /// Register commands for the image viewer widget.
            fn load(cnpy: &mut Canopy) -> Result<()> {}
        }

        impl Widget for ImageView {
            /// Accept focus so key bindings apply to this widget.
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            /// Fill the available space in the terminal view.
            fn layout(&self) -> Layout {}

            /// Render the current image view into the terminal buffer.
            fn render(&mut self, render: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}
        }

        impl FontBanner {
            /// Configure layout options for the banner.
            pub fn with_layout_options(self, options: LayoutOptions) -> Self {}

            /// Configure rendering effects for the banner.
            pub fn with_effects(self, effects: FontEffects) -> Self {}

            /// Configure the banner style path.
            pub fn with_style(self, style: impl Into<String>) -> Self {}

            /// Construct a banner with text and a renderer.
            pub fn new(text: impl Into<String>, renderer: FontRenderer) -> Self {}

            /// Update rendering effects for the banner.
            pub fn set_effects(&mut self, effects: FontEffects) {}

            /// Update the banner renderer.
            pub fn set_renderer(&mut self, renderer: FontRenderer) {}

            /// Update the banner text.
            pub fn set_text(&mut self, text: impl Into<String>) {}
        }

        impl Widget for FontBanner {
            fn layout(&self) -> Layout {}

            fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl FontRenderer {
            /// Create a renderer for the provided font.
            pub fn new(font: Font) -> Self {}
        }
    }

    pub mod terminal {
        //! Terminal emulation widget.

        /// Terminal widget backed by `itty`.
        pub struct Terminal {}

        /// Terminal widget configuration.
        pub struct TerminalConfig {}

        impl CommandNode for Terminal {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Terminal {
            /// Construct a new terminal widget with the provided configuration.
            pub fn new(config: TerminalConfig) -> Self {}
        }

        impl Widget for Terminal {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}

            fn cursor(&self) -> Option<cursor::Cursor> {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn on_event(
                &mut self,
                event: &event::Event,
                ctx: &mut dyn Context,
            ) -> Result<EventOutcome> {
            }

            fn on_mount(&mut self, _ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, _ctx: &mut dyn Context) -> Option<Duration> {}

            fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl Default for TerminalConfig {
            fn default() -> TerminalConfig {}
        }

        impl TerminalConfig {
            /// Configure the command argv to run instead of the default shell.
            pub fn with_command<I, S>(self, command: I) -> Self
            where
                I: IntoIterator<Item = S>,
                S: Into<String>, {
            }

            /// Configure the working directory for the terminal process.
            pub fn with_cwd(self, cwd: impl Into<PathBuf>) -> Self {}

            /// Construct a default terminal configuration.
            pub fn new() -> Self {}
        }
    }

    pub mod text_buffer {
        //! Shared text editing machinery for Input and Editor.
        //! Feature-independent rope storage, editing, and selection helpers.

        /// A text selection expressed as an anchor and head position.
        pub struct Selection {}

        /// Rope-backed text buffer with selection and undo/redo support.
        pub struct TextBuffer {}

        /// A position in the text buffer expressed as a logical line and a char index.
        pub struct TextPosition {
            /// Logical line index (0-based).
            pub line: usize,
            /// Char index within the line (0-based).
            pub column: usize,
        }

        /// A half-open text range expressed in buffer coordinates.
        pub struct TextRange {
            /// Range start position (inclusive).
            pub start: TextPosition,
            /// Range end position (exclusive).
            pub end: TextPosition,
        }

        /// Scoped text edit transaction.
        pub struct TextTransaction<'a> {}

        impl Clone for Selection {
            fn clone(&self) -> Selection {}
        }

        impl Debug for Selection {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for Selection {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl PartialEq for Selection {
            fn eq(&self, other: &Selection) -> bool {}
        }

        impl Selection {
            /// Construct a collapsed selection at a position.
            pub fn caret(position: TextPosition) -> Self {}

            /// Construct a selection from anchor and head positions.
            pub fn new(anchor: TextPosition, head: TextPosition) -> Self {}

            /// Return the anchor position.
            pub fn anchor(self) -> TextPosition {}

            /// Return the head position.
            pub fn head(self) -> TextPosition {}

            /// Return the selection range as a normalized text range.
            pub fn range(self) -> TextRange {}

            /// Return true if the selection is empty.
            pub fn is_empty(self) -> bool {}

            /// Update the head position.
            pub fn set_head(&mut self, head: TextPosition) {}
        }

        impl Clone for TextBuffer {
            fn clone(&self) -> TextBuffer {}
        }

        impl Debug for TextBuffer {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl TextBuffer {
            /// Begin a grouped transaction that commits when the guard is dropped.
            pub fn transaction(&mut self) -> TextTransaction<'_> {}

            /// Begin a grouped transaction.
            pub fn begin_transaction(&mut self) {}

            /// Commit the active transaction, if any.
            pub fn commit_transaction(&mut self) {}

            /// Create a new buffer from an initial string.
            pub fn new(text: impl Into<String>) -> Self {}

            /// Delete the selection or the grapheme after the cursor.
            pub fn delete_forward(&mut self, allow_line_wrap: bool) -> bool {}

            /// Delete the selection or the grapheme before the cursor.
            pub fn delete_backward(&mut self, allow_line_wrap: bool) -> bool {}

            /// Insert text at the cursor, replacing any selection.
            pub fn insert_text(&mut self, text: &str) {}

            /// Move the cursor left by one grapheme.
            pub fn move_left(&mut self, allow_line_wrap: bool) -> bool {}

            /// Move the cursor right by one grapheme.
            pub fn move_right(&mut self, allow_line_wrap: bool) -> bool {}

            /// Move the cursor to the end of the current line.
            pub fn move_line_end(&mut self) {}

            /// Move the cursor to the first non-whitespace character in the line.
            pub fn move_line_first_non_ws(&mut self) {}

            /// Move the cursor to the start of the current line.
            pub fn move_line_start(&mut self) {}

            /// Redo the most recently undone transaction.
            pub fn redo(&mut self) -> bool {}

            /// Replace a range with the provided text.
            pub fn replace_range(&mut self, range: TextRange, text: &str) {}

            /// Replace the cursor and collapse the selection.
            pub fn set_cursor(&mut self, pos: TextPosition) {}

            /// Replace the selection, clamping to bounds.
            pub fn set_selection(&mut self, selection: Selection) {}

            /// Return the closest position for a display column within a line.
            pub fn position_for_column(
                &self,
                line: usize,
                column: usize,
                tab_stop: usize,
            ) -> TextPosition {
            }

            /// Return the current buffer revision.
            pub fn revision(&self) -> u64 {}

            /// Return the current selection.
            pub fn selection(&self) -> Selection {}

            /// Return the cursor position (selection head).
            pub fn cursor(&self) -> TextPosition {}

            /// Return the display column for a position.
            pub fn column_for_position(&self, pos: TextPosition, tab_stop: usize) -> usize {}

            /// Return the end position for a line, optionally including the newline.
            pub fn line_end_position(&self, line: usize, include_newline: bool) -> TextPosition {}

            /// Return the full buffer contents as a string.
            pub fn text(&self) -> String {}

            /// Return the line length in chars, excluding any trailing newline.
            pub fn line_char_len(&self, line: usize) -> usize {}

            /// Return the range a forward delete at `from` would remove.
            ///
            /// At the end of a line the range joins the next line when
            /// `allow_line_wrap` is set. Returns `None` when there is nothing after
            /// the position to delete.
            pub fn forward_delete_range(
                &self,
                from: TextPosition,
                allow_line_wrap: bool,
            ) -> Option<TextRange> {
            }

            /// Return the text in a range.
            pub fn range_text(&self, range: TextRange) -> String {}

            /// Return the text of a logical line without a trailing newline.
            pub fn line_text(&self, line: usize) -> String {}

            /// Return the total number of logical lines.
            pub fn line_count(&self) -> usize {}

            /// Undo the most recent transaction.
            pub fn undo(&mut self) -> bool {}
        }

        impl Clone for TextPosition {
            fn clone(&self) -> TextPosition {}
        }

        impl Debug for TextPosition {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for TextPosition {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl Hash for TextPosition {
            fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
        }

        impl Ord for TextPosition {
            fn cmp(&self, other: &Self) -> Ordering {}
        }

        impl PartialEq for TextPosition {
            fn eq(&self, other: &TextPosition) -> bool {}
        }

        impl PartialOrd for TextPosition {
            fn partial_cmp(&self, other: &Self) -> Option<Ordering> {}
        }

        impl TextPosition {
            /// Create a new text position.
            pub fn new(line: usize, column: usize) -> Self {}
        }

        impl Clone for TextRange {
            fn clone(&self) -> TextRange {}
        }

        impl Debug for TextRange {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Eq for TextRange {
            #[doc(hidden)]
            fn assert_fields_are_eq(&self) {}
        }

        impl Hash for TextRange {
            fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
        }

        impl PartialEq for TextRange {
            fn eq(&self, other: &TextRange) -> bool {}
        }

        impl TextRange {
            /// Construct a text range.
            pub fn new(start: TextPosition, end: TextPosition) -> Self {}

            /// Return a range with start/end ordered.
            pub fn normalized(self) -> Self {}

            /// Return true if the range is empty.
            pub fn is_empty(self) -> bool {}
        }

        impl Deref for TextTransaction<'_> {
            fn deref(&self) -> &Self::Target {}

            type Target = TextBuffer;
        }

        impl DerefMut for TextTransaction<'_> {
            fn deref_mut(&mut self) -> &mut Self::Target {}
        }

        impl Drop for TextTransaction<'_> {
            fn drop(&mut self) {}
        }
    }

    /// Monotonic key for list items.
    pub struct AutoKey(_);

    /// A simple box container around its children.
    pub struct Border {}

    /// Defines the set of glyphs used to draw the box.
    pub struct BoxGlyphs {
        /// Top-left corner glyph.
        pub topleft: char,
        /// Top-right corner glyph.
        pub topright: char,
        /// Bottom-left corner glyph.
        pub bottomleft: char,
        /// Bottom-right corner glyph.
        pub bottomright: char,
        /// Horizontal border glyph.
        pub horizontal: char,
        /// Vertical border glyph.
        pub vertical: char,
    }

    /// Button widget that triggers a command when clicked.
    pub struct Button {}

    /// Canvas width behavior for text widgets.
    pub enum CanvasWidth {
        /// Match the view width.
        View,
        /// Use the maximum wrapped line width.
        Intrinsic,
        /// Use a fixed canvas width.
        Fixed(u32),
    }

    /// Container that centers its child within available space.
    ///
    /// For a dimmed overlay, push an effect on the background content with
    /// `c.push_effect(background_id, effects::brightness(0.5))`. This container
    /// stays at full brightness because it is a sibling of the dimmed content, not
    /// a descendant. Insert it as a sibling inside a parent that uses `Stack`
    /// layout so it can overlay the existing view.
    pub struct Center;

    /// A dropdown widget for single-value selection.
    ///
    /// When collapsed, displays the currently selected item with a dropdown
    /// indicator. When expanded, displays all options for selection.
    pub struct Dropdown<T>
    where
        T: Label, {}

    /// A frame around an element with optional title and indicators.
    pub struct Frame {}

    /// Widget that renders an image into terminal cells.
    pub struct ImageView {}

    /// Single-line text input widget.
    pub struct Input {}

    /// A typed list container for widget items.
    ///
    /// List items are actual widgets in the tree, enabling composition and focus
    /// management. The list arranges items vertically and supports scrolling.
    ///
    /// Items must implement the [`Selectable`] trait so the list can manage their
    /// selection state independently of focus.
    pub struct List<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue = AutoKey> {}

    /// Container that adds padding around its child.
    pub struct Pad {}

    /// Panes manages a set of child nodes arranged in a 2d grid.
    pub struct Panes {}

    /// A Root widget that lives at the base of a Canopy app.
    pub struct Root {}

    /// A multi-select widget with checkbox-style items.
    ///
    /// Items can be toggled on/off independently. The selected indices are tracked
    /// in the order they were selected, allowing for ordered selection if needed.
    pub struct Selector<T>
    where
        T: Label, {}

    /// Multiline text widget with wrapping and scrolling.
    pub struct Text {}

    /// A vertical stack that arranges children with fixed or flex heights.
    pub struct VStack {}

    /// Policy for publishing an input value in semantic snapshots.
    pub enum ValueExposure {
        #[default]
        /// Omit the value from semantics.
        Omit,
        /// Publish the raw single-line value.
        Public,
        /// Mark the value as sensitive and always omit it from semantics.
        Sensitive,
    }

    /// An item that renders as one line of text.
    pub trait Label {
        /// Return the display label for this item.
        fn label(&self) -> &str;
    }

    /// Trait for widgets that can be selected in a list.
    ///
    /// Items in a `List` must implement this trait so the list can manage
    /// their selection state. Selection is independent of focus - an item
    /// remains selected even when the list loses focus.
    pub trait Selectable: Widget {
        /// Set the selection state of this item.
        fn set_selected(&mut self, selected: bool);
    }

    /// Double line Unicode box drawing set.
    pub const DOUBLE: BoxGlyphs = _;

    /// Round corner thin Unicode box drawing set.
    pub const ROUND: BoxGlyphs = _;

    /// Single line thin Unicode box drawing set.
    pub const SINGLE: BoxGlyphs = _;

    /// Single line thick Unicode box drawing set.
    pub const SINGLE_THICK: BoxGlyphs = _;

    /// Wrap `child` in a new `widget` node and return the wrapper's typed id.
    ///
    /// The child keeps its identity: it is detached from its current parent and
    /// reattached under the wrapper.
    pub fn wrap<W: 'static + Widget>(
        c: &mut dyn Context,
        child: impl Into<canopy::NodeId>,
        widget: W,
    ) -> canopy::error::Result<canopy::TypedId<W>> {
    }

    impl Border {
        /// Build a box with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Construct a box.
        pub fn new() -> Self {}

        /// Enable interior fill using the default fill style name.
        pub fn with_fill(self) -> Self {}

        /// Set the border paint role while preserving inherited component layers.
        pub fn with_border_style(self, style: impl Into<String>) -> Self {}
    }

    impl CommandNode for Border {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for Border {
        fn default() -> Self {}
    }

    impl Widget for Border {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl Button {
        /// Build a button that dispatches a command when clicked.
        pub fn with_command(self, command: CommandCall) -> Self {}

        /// Build a button with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Construct a new button with a label.
        pub fn new(label: impl Into<String>) -> Self {}

        /// Set whether the button is active.
        pub fn set_active(&mut self, active: bool) {}

        /// Trigger the button action.
        pub fn press(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_press() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_press() -> &'static canopy::commands::CommandSpec {}
    }

    impl CommandNode for Button {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Widget for Button {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl Center {
        /// Create a new Center widget.
        pub fn new() -> Self {}
    }

    impl CommandNode for Center {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for Center {
        fn default() -> Self {}
    }

    impl Widget for Center {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl Clone for AutoKey {
        fn clone(&self) -> AutoKey {}
    }

    impl Debug for AutoKey {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for AutoKey {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl Hash for AutoKey {
        fn hash<__H: hash::Hasher>(&self, state: &mut __H) {}
    }

    impl PartialEq for AutoKey {
        fn eq(&self, other: &AutoKey) -> bool {}
    }

    impl ToArgValue for AutoKey {
        fn to_arg_value(self) -> ArgValue {}
    }

    impl Clone for BoxGlyphs {
        fn clone(&self) -> BoxGlyphs {}
    }

    impl Debug for BoxGlyphs {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for BoxGlyphs {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for BoxGlyphs {
        fn eq(&self, other: &BoxGlyphs) -> bool {}
    }

    impl Clone for CanvasWidth {
        fn clone(&self) -> CanvasWidth {}
    }

    impl Debug for CanvasWidth {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Eq for CanvasWidth {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for CanvasWidth {
        fn eq(&self, other: &CanvasWidth) -> bool {}
    }

    impl Clone for ValueExposure {
        fn clone(&self) -> ValueExposure {}
    }

    impl Debug for ValueExposure {
        fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
    }

    impl Default for ValueExposure {
        fn default() -> ValueExposure {}
    }

    impl Eq for ValueExposure {
        #[doc(hidden)]
        fn assert_fields_are_eq(&self) {}
    }

    impl PartialEq for ValueExposure {
        fn eq(&self, other: &ValueExposure) -> bool {}
    }

    impl CommandNode for Frame {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for Frame {
        fn default() -> Self {}
    }

    impl Frame {
        /// Build a frame with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Build a frame with a specified title.
        pub fn with_title(self, title: impl Into<String>) -> Self {}

        /// Construct a frame.
        pub fn new() -> Self {}
    }

    impl Widget for Frame {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl CommandNode for ImageView {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl ImageView {
        /// Create a new image view widget from a file path.
        pub fn from_path(path: impl AsRef<Path>) -> Result<Self> {}

        /// Create a new image view widget.
        pub fn new(image: &RgbaImage) -> Self {}

        /// Pan by one step in the specified direction.
        /// @param dir The pan direction.
        pub fn pan(&mut self, ctx: &mut dyn Context, dir: FocusDirection) -> Result<()> {}

        /// Zoom around the view center.
        /// @param dir The zoom direction.
        pub fn zoom(&mut self, ctx: &mut dyn Context, dir: ZoomDirection) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_pan(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_zoom(dir: ZoomDirection) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_pan() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_zoom() -> &'static canopy::commands::CommandSpec {}
    }

    impl Loader for ImageView {
        /// Register commands for the image viewer widget.
        fn load(cnpy: &mut Canopy) -> Result<()> {}
    }

    impl Widget for ImageView {
        /// Accept focus so key bindings apply to this widget.
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        /// Fill the available space in the terminal view.
        fn layout(&self) -> Layout {}

        /// Render the current image view into the terminal buffer.
        fn render(&mut self, render: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}
    }

    impl CommandNode for Input {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Input {
        /// Configure whether semantic snapshots expose this input's value.
        pub fn with_value_exposure(self, exposure: ValueExposure) -> Self {}

        /// Construct a new input with initial text.
        pub fn new(txt: impl Into<String>) -> Self {}

        /// Delete a character at the input location.
        pub fn backspace(&mut self, _c: &mut dyn Context) {}

        /// Move the cursor left.
        pub fn left(&mut self, _c: &mut dyn Context) {}

        /// Move the cursor right.
        pub fn right(&mut self, _c: &mut dyn Context) {}

        /// Replace the input value and reset the cursor.
        pub fn set_value(&mut self, value: impl Into<String>) {}

        /// Return the raw input value without padding.
        pub fn value(&self) -> &str {}

        /// Set the semantic label without changing the displayed value.
        pub fn with_label(self, label: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_backspace() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_left() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_right() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_backspace() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_left() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_right() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Input {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn cursor(&self) -> Option<cursor::Cursor> {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, _ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, _ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl CommandNode for Pad {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Pad {
        /// Create a pad with the provided edge padding.
        pub fn new(padding: Edges) -> Self {}

        /// Create a pad with uniform padding on all sides.
        pub fn uniform(padding: u32) -> Self {}
    }

    impl Widget for Pad {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl CommandNode for Panes {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for Panes {
        fn default() -> Self {}
    }

    impl Panes {
        /// Construct panes with no children.
        pub fn new() -> Self {}

        /// Delete the focus node. If a column ends up empty, it is removed.
        pub fn delete_focus(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Insert a node in a new column.
        pub fn insert_col(&mut self, c: &mut dyn Context, n: impl Into<NodeId>) -> Result<()> {}

        /// Move focus by a signed column offset (wraps around).
        pub fn focus_column(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus_column(delta: i32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus_column() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Panes {
        fn name(&self) -> NodeName {}

        fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
    }

    impl CommandNode for Root {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for Root {
        fn default() -> Self {}
    }

    impl Loader for Root {
        fn load(c: &mut Canopy) -> Result<()> {}
    }

    impl Root {
        /// Construct a root widget wrapping the application and inspector nodes.
        pub fn new() -> Self {}

        /// Dump diagnostic information about the tree, focus, and bindings.
        pub fn dump_diagnostics(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Exit from the program, restoring terminal state. If help or inspector is
        /// open, close them first.
        pub fn quit(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Hide the help modal.
        pub fn hide_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Hide the inspector.
        pub fn hide_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// If we're currently focused in the inspector, shift focus into the app
        /// pane instead.
        pub fn focus_app(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Install the application, shared help, and enabled developer tools.
        pub fn install<W>(self, canopy: &mut Canopy, app: W) -> Result<TypedId<W>>
        where
            W: 'static + Widget, {
        }

        /// Move focus in the specified direction.
        /// @param direction The direction to move focus.
        pub fn focus(&mut self, c: &mut dyn Context, direction: FocusDirection) -> Result<()> {}

        /// Show the help modal with contextual bindings and commands.
        pub fn show_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Show the inspector.
        pub fn show_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Start with the inspector open.
        pub fn with_inspector(self, state: bool) -> Self {}

        /// Toggle help modal visibility.
        pub fn toggle_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Toggle inspector visibility.
        pub fn toggle_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_dump_diagnostics() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus(direction: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus_app() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_hide_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_hide_inspector() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_quit() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_show_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_show_inspector() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle_inspector() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_dump_diagnostics() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus_app() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_hide_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_hide_inspector() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_quit() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_show_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_show_inspector() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle_inspector() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Root {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl CommandNode for Text {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Selectable for Text {
        fn set_selected(&mut self, selected: bool) {}
    }

    impl Text {
        /// Add a fixed width for wrapping.
        pub fn with_wrap_width(self, width: u32) -> Self {}

        /// Configure the canvas width behavior.
        pub fn with_canvas_width(self, width: CanvasWidth) -> Self {}

        /// Construct a text widget with raw content.
        pub fn new(raw: impl Into<String>) -> Self {}

        /// Page vertically through the text.
        /// Positive values move down; negative values move up.
        /// @param delta Signed page delta. Positive moves down and negative moves
        /// up.
        pub fn page(&mut self, c: &mut dyn Context, delta: i32) {}

        /// Replace the raw text content.
        pub fn set_text(&mut self, raw: impl Into<String>) {}

        /// Scroll by one line in the specified direction.
        /// @param dir The direction to scroll.
        pub fn scroll(&mut self, c: &mut dyn Context, dir: FocusDirection) {}

        /// Scroll to an absolute content position.
        pub fn scroll_to(&mut self, c: &mut dyn Context, x: u32, y: u32) {}

        /// Set the tab stop width for tab expansion.
        pub fn with_tab_stop(self, tab_stop: usize) -> Self {}

        /// Set the text rendering style when selected.
        pub fn with_selected_style(self, style: impl Into<String>) -> Self {}

        /// Set the text rendering style.
        pub fn with_style(self, style: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll_to(x: u32, y: u32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll_to() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Text {
        fn canvas(&self, view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl CommandNode for VStack {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Default for VStack {
        fn default() -> Self {}
    }

    impl VStack {
        /// Add a fixed-height row.
        pub fn push_fixed(self, node: impl Into<NodeId>, height: u32) -> Self {}

        /// Add a flex row with a weight.
        pub fn push_flex(self, node: impl Into<NodeId>, weight: u32) -> Self {}

        /// Construct an empty vertical stack.
        pub fn new() -> Self {}
    }

    impl Widget for VStack {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}
    }

    impl<T> CommandNode for Dropdown<T>
    where
        T: 'static + Label,
    {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<T> Dropdown<T>
    where
        T: 'static + Label,
    {
        /// Collapse without changing selection.
        pub fn cancel(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Confirm the highlighted selection and collapse.
        pub fn confirm(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Create a new dropdown with the given items.
        ///
        /// Returns an error if `items` is empty.
        pub fn new(items: Vec<T>) -> Result<Self> {}

        /// Get the currently selected index.
        pub fn selected_index(&self) -> usize {}

        /// Get the currently selected item.
        pub fn selected(&self) -> &T {}

        /// Move highlight by a signed offset (when expanded).
        pub fn select_by(&mut self, _c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Toggle the dropdown expanded state.
        pub fn toggle(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_cancel() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_confirm() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_cancel() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_confirm() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle() -> &'static canopy::commands::CommandSpec {}
    }

    impl<T> Widget for Dropdown<T>
    where
        T: 'static + Label,
    {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, _view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl<T> CommandNode for Selector<T>
    where
        T: 'static + Label,
    {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<T> Selector<T>
    where
        T: 'static + Label,
    {
        /// Clear all selections.
        pub fn clear(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Create a new selector with the given items.
        pub fn new(items: Vec<T>) -> Self {}

        /// Get references to the selected items in selection order.
        pub fn selected_items(&self) -> Vec<&T> {}

        /// Move focus by a signed offset.
        pub fn select_by(&mut self, _c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move focus to the first item.
        pub fn select_first(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Move focus to the last item.
        pub fn select_last(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Select all items.
        pub fn select_all(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Toggle selection of the focused item.
        pub fn toggle(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_clear() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_all() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_first() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_last() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_all() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_first() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_last() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle() -> &'static canopy::commands::CommandSpec {}
    }

    impl<T> Widget for Selector<T>
    where
        T: 'static + Label,
    {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, _view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl<W: 'static + Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> Widget for List<W, K> {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

        fn layout(&self) -> Layout {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> CommandNode for List<W, K> {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> Default for List<W, K> {
        fn default() -> Self {}
    }

    impl<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> List<W, K> {
        /// Build a list that dispatches a command when a row is activated.
        pub fn with_on_activate(self, command: CommandCall) -> Self {}

        /// Build a list with a list-level selection indicator.
        /// Repeat controls whether the indicator renders on every visible line.
        pub fn with_selection_indicator(
            self,
            style: impl Into<String>,
            text: impl Into<String>,
            repeat: bool,
        ) -> Self {
        }

        /// Clear all items from the list.
        pub fn clear(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        /// Construct an empty list.
        pub fn new() -> Self {}

        /// Delete the currently selected item.
        pub fn delete_selected(&mut self, ctx: &mut dyn Context) -> Result<bool> {}

        /// Move selection by a signed offset.
        pub fn select_by(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move selection by pages.
        /// Positive values move down; negative values move up.
        /// @param delta Signed page delta. Positive moves down and negative moves
        /// up.
        pub fn page(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move selection to the first item.
        pub fn select_first(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Move selection to the last item.
        pub fn select_last(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Reconcile domain keys while retaining widgets and selection for
        /// surviving keys.
        ///
        /// Duplicate keys fail before callbacks run. Updates have the same
        /// structural rollback boundary as [`KeyedChildren::reconcile`]. If
        /// selection is removed, the next surviving old neighbor wins, then the
        /// previous neighbor.
        pub fn reconcile<I, C, U>(
            &mut self,
            ctx: &mut dyn Context,
            desired: I,
            create: C,
            update: U,
        ) -> Result<Vec<TypedId<W>>>
        where
            C: FnMut(&K) -> Result<W>,
            I: IntoIterator<Item = K>,
            U: FnMut(&K, TypedId<W>, &mut dyn Context) -> Result<()>, {
        }

        /// Return the stable key of the selected row.
        pub fn selected_key(&self) -> Option<&K> {}

        /// Returns the currently selected index.
        pub fn selected_index(&self) -> Option<usize> {}

        /// Returns the number of items in the list.
        pub fn len(&self) -> usize {}

        /// Returns the typed ID of the currently selected item.
        pub fn selected_item(&self) -> Option<TypedId<W>> {}

        /// Returns the typed ID of the item at the given index.
        pub fn item(&self, index: usize) -> Option<TypedId<W>> {}

        /// Returns true if the list is empty.
        pub fn is_empty(&self) -> bool {}

        /// Scroll the view by one line in the specified direction.
        /// @param dir The direction to scroll.
        pub fn scroll(&mut self, c: &mut dyn Context, dir: FocusDirection) {}

        /// Select a domain key, returning an error when it is absent.
        pub fn select_key(&mut self, ctx: &mut dyn Context, key: &K) -> Result<()> {}

        /// Select an item at the given index.
        pub fn select(&mut self, ctx: &mut dyn Context, index: usize) -> Result<()> {}

        /// Set the semantic label of the collection.
        pub fn with_label(self, label: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_clear() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_delete_selected() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_first() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_last() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_delete_selected() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_first() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_last() -> &'static canopy::commands::CommandSpec {}
    }

    impl<W: Selectable> List<W, AutoKey> {
        /// Append a widget with a fresh automatic key.
        pub fn append(&mut self, ctx: &mut dyn Context, widget: W) -> Result<TypedId<W>> {}

        /// Insert a widget with a fresh automatic key at the clamped index.
        pub fn insert(
            &mut self,
            ctx: &mut dyn Context,
            index: usize,
            widget: W,
        ) -> Result<TypedId<W>> {
        }
    }
}
