// @generated by `ruskel-snapshot`; do not edit.
//
// Package: canopy-mcp
// Publish: crates.io
// Workspace dependencies: canopy
// Workspace dependents: canopyctl, gyms, hello, todo

//! MCP and smoke-test helpers for canopy applications.

use std::{
    fmt::{Debug, Display},
    path::{Path, PathBuf},
    process::ExitCode,
};

use canopy::{
    Canopy, CanopyBuilder,
    commands::CommandError,
    error::ScriptErrorKind,
    geom::Size,
    script::{AutomationHandle, FixtureInfo, ScriptAssertion, ScriptCheckDiagnostic},
    terminal::RunOptions,
};
use ruau_script_api::ScriptApiEntry;
use schemars::JsonSchema;
use serde_core::{de::Deserialize, ser::Serialize};
use serde_json::Value;
use tmcp::schema::CallToolResult;

/// Startup file a configuration home must hold to be mounted.
pub const INIT_SCRIPT: &str = "init.luau";

/// Mount a user configuration on a [`CanopyBuilder`].
// Not dyn-compatible.
pub trait UserConfig {
    /// Mount `home` as the trusted `@user` root when it holds
    /// [`INIT_SCRIPT`], and otherwise run `defaults` as the startup script.
    ///
    /// `defaults` follows the startup-script contract: it defines `setup()`.
    #[must_use]
    fn user_config(self, home: Option<&ConfigHome>, defaults: &'static str) -> Self;
}

impl UserConfig for CanopyBuilder {}

/// Shared application constructor with an explicit domain-state declaration.
///
/// Factory operations are synchronous and may execute application scripts.
/// Async callers should construct, use, and drop each application on one
/// blocking worker. The headless MCP server supplies bounded workers itself.
#[derive(Clone)]
pub struct AppFactory {/* private fields */}

impl AppFactory {
    /// Bootstrap at requested dimensions, validated before factory invocation.
    pub fn bootstrap(&self, request: &BootstrapRequest) -> crate::Result<BootstrapResponse>;

    /// Evaluate a Luau script against a fresh headless app.
    pub fn evaluate(&self, request: &ScriptEvalRequest) -> EvalReport;

    /// Render and return the app's Luau API definition.
    pub fn script_api(&self) -> crate::Result<String>;
}

impl AppFactory {
    /// Build one fully configured application instance.
    pub fn build(&self) -> crate::Result<Canopy>;

    /// Read the application declaration without constructing its UI.
    pub fn metadata(&self) -> &AppMetadata;

    /// Declare application metadata and the constructor for built instances.
    pub fn new<F>(metadata: AppMetadata, factory: F) -> Self
    where
        F: 'static + Fn() -> crate::Result<Canopy> + Send + Sync;
}

/// Identity and domain reset behavior declared by an application factory.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct AppMetadata {
    /// Stable application name used by replay compatibility checks.
    pub app: String,
    /// Domain reset behavior, independent of UI reconstruction.
    pub reset: ResetPolicy,
}

/// Request payload for applying a named fixture to a live app.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(crate = "::tmcp::__private::serde")]
#[schemars(crate = "::tmcp::__private::schemars")]
pub struct ApplyFixtureRequest {
    /// Registered fixture name.
    pub name: String,
}

impl JsonSchema for ApplyFixtureRequest {}

/// Response returned after a fixture is applied to a live app.
#[derive(Clone, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ApplyFixtureResponse {
    /// Name of the applied fixture.
    pub applied: String,
}

impl JsonSchema for ApplyFixtureResponse {}

/// Compact command availability record returned by bootstrap.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct BootstrapCommand {
    /// Command name relative to its owner.
    pub name: String,
    /// Widget owner name.
    pub owner: String,
    /// Whether the command currently resolves.
    pub available: bool,
    /// Eligibility, when an owner resolves.
    pub status: Option<String>,
    /// User-facing reason for disabled eligibility.
    pub disabled_reason: Option<String>,
    /// Missing originating event or row context, separate from eligibility.
    pub missing_requirements: Vec<String>,
}

impl JsonSchema for BootstrapCommand {}

/// Compact script journal record returned by bootstrap.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct BootstrapJournalEntry {
    /// Monotonic journal id.
    pub id: u64,
    /// Where the source came from, such as `eval` or `startup:NAME`.
    pub origin: String,
    /// Whether the evaluation completed successfully.
    pub ok: bool,
    /// Number of logs emitted by this evaluation.
    pub log_count: usize,
    /// Number of assertions emitted by this evaluation.
    pub assertion_count: usize,
    /// Wall-clock duration in milliseconds.
    pub duration_ms: u64,
}

impl JsonSchema for BootstrapJournalEntry {}

/// Optional dimensions for bootstrap replay preflight.
#[derive(Clone, Debug, Default, Deserialize<'de>, PartialEq, Serialize)]
#[serde(crate = "::tmcp::__private::serde")]
#[schemars(crate = "::tmcp::__private::schemars")]
pub struct BootstrapRequest {
    /// Requested headless screen, or a live screen compatibility check.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen: Option<ScreenSize>,
}

impl JsonSchema for BootstrapRequest {}

/// Bootstrap payload for an agent entering a Canopy app.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct BootstrapResponse {
    /// Execution identity and domain reset behavior for this bootstrap
    /// instance.
    pub metadata: ExecutionMetadata,
    /// Operating guide for the automation surface.
    pub guide: String,
    /// Compact discovery inventory for the generated API.
    pub api_sources: Vec<ScriptApiEntry>,
    /// Registered fixtures.
    pub fixtures: Vec<FixtureInfo>,
    /// Availability from the root used by top-level script evaluation.
    pub default_commands: Vec<BootstrapCommand>,
    /// Availability from the currently focused node.
    pub focus_commands: Vec<BootstrapCommand>,
    /// Recent script journal entries.
    pub journal: Vec<BootstrapJournalEntry>,
}

impl JsonSchema for BootstrapResponse {}

/// A resolved directory for a user's Luau configuration.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ConfigHome {/* private fields */}

impl ConfigHome {
    /// Return whether the home holds [`INIT_SCRIPT`], and so is mounted.
    pub fn has_init(&self) -> bool;

    /// Use `path` as the configuration home.
    pub fn new(path: impl Into<PathBuf>) -> Self;

    /// Return the home directory.
    pub fn path(&self) -> &Path;

    /// Resolve the configuration home of `app` for a launch in `mode`.
    ///
    /// Headless MCP is hermetic: it resolves to no home, and an explicit
    /// `flag` there is an error. `no_config` also resolves to no home, and
    /// conflicts with an explicit `flag`. Otherwise the home is `flag`, then
    /// the `{APP}_CONFIG_HOME` environment variable, then `$HOME/.{app}`.
    pub fn resolve(
        app: &str,
        flag: Option<PathBuf>,
        no_config: bool,
        mode: &LaunchMode,
    ) -> crate::Result<Option<Self>>;

    /// Write `defaults` as the home's [`INIT_SCRIPT`] unless one exists,
    /// creating the directory. Return whether it wrote.
    ///
    /// This is opt-in. An existing file, including one a concurrent first run
    /// just created, is never replaced.
    pub fn write_defaults(&self, defaults: &str) -> std::io::Result<bool>;
}

/// Errors returned by `canopy-mcp`.
#[derive(Debug, Display, std::error::Error)]
pub enum Error {
    /// A canopy runtime error.
    #[error(transparent)]
    Canopy(canopy::error::Error),
    /// A canopy command conversion error.
    #[error(transparent)]
    Command(CommandError),
    /// An I/O error.
    #[error(transparent)]
    Io(std::io::Error),
    /// An MCP transport or protocol error.
    #[error(transparent)]
    Tmcp(tmcp::Error),
    /// The application factory failed to build an app instance.
    #[error("app setup failed: {0}")]
    App(Box<dyn Send + std::error::Error + Sync>),
    /// The UDS listener thread panicked while shutting down.
    #[error("UDS listener thread panicked")]
    ListenerThreadPanicked,
    /// The UDS listener stopped before reporting startup readiness.
    #[error("UDS listener failed to report readiness")]
    ListenerReadinessClosed,
    /// The user configuration home could not be resolved.
    #[error("configuration: {0}")]
    Config(String),
    /// A smoke suite did not resolve to any Luau scripts.
    #[error("no .luau scripts found under {0}")]
    NoScripts(PathBuf),
}

impl Error {
    /// Wrap an application-specific setup error.
    pub fn app(error: impl Into<Box<dyn Send + std::error::Error + Sync>>) -> Self;
}

impl From<CommandError> for Error {}

impl From<canopy::error::Error> for Error {}

impl From<std::io::Error> for Error {}

impl From<tmcp::Error> for Error {}

/// Structured response for the `script_eval` tool and smoke runner.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct EvalReport {
    /// Execution identity and domain reset behavior for this request.
    pub metadata: ExecutionMetadata,
    /// Whether the script completed successfully.
    pub success: bool,
    /// Final task state for the evaluation.
    pub state: ScriptTaskState,
    /// Optional JSON-serializable script return value.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub value: Option<Value>,
    /// Log lines emitted during evaluation.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub logs: Vec<String>,
    /// Assertion outcomes recorded during evaluation.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub assertions: Vec<ScriptAssertion>,
    /// Typecheck diagnostics captured before execution.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub diagnostics: Vec<ScriptCheckDiagnostic>,
    /// Timing information for the request.
    pub timing: ScriptTiming,
    /// Error payload when evaluation fails.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<ScriptErrorInfo>,
}

impl EvalReport {
    /// Encode the outcome as an MCP tool result.
    pub fn to_tool_result(&self) -> CallToolResult;
}

impl JsonSchema for EvalReport {}

/// Owned execution metadata returned even when an evaluation fails.
#[derive(Clone, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ExecutionMetadata {
    /// Stable application identity.
    pub app: String,
    /// UI lifetime used by this evaluation.
    pub execution: ExecutionMode,
    /// Opaque identity of the application session, not a durable node
    /// reference.
    pub instance_id: String,
    /// Evaluated or requested screen, absent when live metadata could not be
    /// observed.
    pub screen: Option<ScreenSize>,
    /// The application's declared domain reset contract.
    pub reset: ResetPolicy,
    /// Fixture applied before this evaluation, if any. A fixture resets the
    /// domain state it covers, whatever the reset policy.
    pub fixture: Option<String>,
    /// Generated API identity, absent only when preparation could not obtain
    /// it.
    pub api_digest: Option<String>,
}

impl JsonSchema for ExecutionMetadata {}

/// Whether evaluation constructs a new UI or uses the running application.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "kebab-case")]
pub enum ExecutionMode {
    /// Each evaluation constructs a fresh application UI.
    #[default]
    FreshAppPerEval,
    /// Evaluations share one running application.
    LiveSession,
}

impl JsonSchema for ExecutionMode {}

/// Launcher mode for a Canopy application.
pub enum LaunchMode {
    /// Run the interactive terminal UI.
    Run {
        /// Optional live MCP Unix-domain socket path.
        mcp_socket: Option<PathBuf>,
        /// Terminal adapter policy for the run loop.
        options: RunOptions,
    },
    /// Serve the headless MCP automation server over stdio.
    HeadlessMcp,
}

/// Application-declared reset behavior for domain data.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ResetPolicy {
    /// Domain state can persist outside the UI instance.
    #[default]
    External,
    /// Each factory invocation owns independent domain state.
    Isolated,
}

impl JsonSchema for ResetPolicy {}

/// Result type used by `canopy-mcp`.
pub type Result<T> = Result<T, Error>;

/// Terminal dimensions in cells, serialized independently of internal geometry.
#[derive(Clone, Copy, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ScreenSize {
    /// Number of columns.
    pub width: u32,
    /// Number of rows.
    pub height: u32,
}

impl ScreenSize {
    /// Reject empty or excessive headless dimensions before constructing an
    /// app.
    pub fn validate(self) -> crate::Result<()>;
}

impl From<ScreenSize> for Size {}

impl From<Size> for ScreenSize {}

impl JsonSchema for ScreenSize {}

/// Error details included in a failed script evaluation.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
pub struct ScriptErrorInfo {
    /// Pipeline stage that failed.
    #[serde(rename = "type")]
    pub error_type: ScriptErrorType,
    /// Stable host error category such as `no_target` or `unknown_command`,
    /// when the failure carried structured fields.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<ScriptErrorKind>,
    /// Command id when the error came from command dispatch.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub command: Option<String>,
    /// Owner name when the error came from node-target resolution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub owner: Option<String>,
    /// Human-readable error message.
    pub message: String,
}

impl JsonSchema for ScriptErrorInfo {}

/// Pipeline stage that caused a script evaluation to fail.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ScriptErrorType {
    /// Application construction or initial rendering failed.
    Build,
    /// Luau typechecking failed.
    Typecheck,
    /// Evaluation exceeded its cooperative timeout.
    Timeout,
    /// Evaluation failed while running.
    Runtime,
    /// Evaluation was explicitly cancelled.
    Cancelled,
    /// Request metadata or options were invalid.
    Invalid,
}

impl JsonSchema for ScriptErrorType {}

/// Request payload for the `script_eval` tool.
#[derive(Clone, Debug, Deserialize<'de>, PartialEq, Serialize)]
#[serde(crate = "::tmcp::__private::serde")]
#[schemars(crate = "::tmcp::__private::schemars")]
pub struct ScriptEvalRequest {
    /// Luau source code to execute.
    pub source: String,
    /// Optional named fixture applied before evaluation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub fixture: Option<String>,
    /// Optional evaluation timeout in milliseconds.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub timeout_ms: Option<u64>,
    /// Optional headless dimensions; live requests may only confirm current
    /// dimensions.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub screen: Option<ScreenSize>,
}

impl ScriptEvalRequest {
    /// Construct a request with default fixture, timeout, and screen options.
    pub fn new(source: impl Into<String>) -> Self;
}

impl JsonSchema for ScriptEvalRequest {}

/// Result of running one smoke script.
#[derive(Clone, Debug, PartialEq)]
pub struct ScriptOutcome {
    /// Script path on disk.
    pub path: PathBuf,
    /// Fixture derived for this script, if any.
    pub fixture: Option<String>,
    /// Structured script outcome, carrying success, timing, and error details.
    pub outcome: EvalReport,
}

/// Evaluation task state exposed to automation callers.
#[derive(Clone, Copy, Debug, Deserialize<'de>, Eq, PartialEq, Serialize)]
#[serde(rename_all = "snake_case")]
pub enum ScriptTaskState {
    /// Evaluation completed successfully.
    Completed,
    /// Evaluation failed before completion.
    Failed,
    /// Evaluation stopped at the cooperative timeout boundary.
    TimedOut,
    /// Evaluation was explicitly cancelled.
    Cancelled,
}

impl From<ScriptErrorType> for ScriptTaskState {}

impl JsonSchema for ScriptTaskState {}

/// Timing information for a script evaluation.
#[derive(Clone, Debug, Default, Deserialize<'de>, Eq, PartialEq, Serialize)]
pub struct ScriptTiming {
    /// Time spent constructing and rendering the headless app.
    pub build_ms: u64,
    /// Time spent executing the script and final render.
    pub exec_ms: u64,
    /// Total wall-clock time for the request.
    pub total_ms: u64,
}

impl JsonSchema for ScriptTiming {}

/// Configuration for a smoke-suite run.
#[derive(Clone, Debug, PartialEq)]
pub struct SuiteConfig {
    /// Root directory to scan for `.luau` scripts when no explicit script list
    /// is provided.
    pub suite_dir: PathBuf,
    /// Optional subset of scripts to run. Relative paths are resolved against
    /// `suite_dir`.
    pub scripts: Vec<PathBuf>,
    /// Optional per-script timeout in milliseconds.
    pub timeout_ms: Option<u64>,
    /// Stop after the first failed script.
    pub fail_fast: bool,
}

impl SuiteConfig {
    /// Construct a config using a suite directory and default options.
    pub fn new(suite_dir: impl Into<PathBuf>) -> Self;
}

/// Aggregated result for a smoke suite.
#[derive(Clone, Debug, PartialEq)]
pub struct SuiteOutcome {
    /// Per-script results in execution order.
    pub scripts: Vec<ScriptOutcome>,
}

impl SuiteOutcome {
    /// Return true when all smoke scripts passed.
    pub fn success(&self) -> bool;
}

/// One planned smoke script with its resolved fixture and evaluation request.
#[derive(Clone, Debug, PartialEq)]
pub struct SuiteScript {
    /// Script path on disk.
    pub path: PathBuf,
    /// Evaluation request carrying the script source, its derived fixture,
    /// and suite options.
    pub request: ScriptEvalRequest,
}

/// Handle for a running live UDS MCP listener.
pub struct UdsServerHandle {/* private fields */}

impl UdsServerHandle {
    /// Stop the listener and remove the socket path.
    pub fn stop(self) -> crate::Result<()>;
}

impl Drop for UdsServerHandle {}

/// Launch a Canopy app in the selected mode, and return the process exit
/// code.
///
/// The caller owns CLI parsing and app-specific configuration, including
/// printing the Luau API. This function owns the repeated framework wiring:
/// headless MCP, live MCP, and the terminal runloop.
pub fn launch(factory: AppFactory, mode: LaunchMode) -> crate::Result<ExitCode>;

/// Resolve the ordered smoke scripts for a suite run into evaluation requests.
///
/// Reading the source and deriving the fixture happen here so `run_suite` and
/// external runners share one plan.
pub fn plan_suite(config: &SuiteConfig) -> crate::Result<Vec<SuiteScript>>;

/// Run a smoke suite against fresh headless app instances.
pub fn run_suite(factory: &AppFactory, config: &SuiteConfig) -> crate::Result<SuiteOutcome>;

/// Serve `bootstrap`, `script_eval`, and `script_api` over stdio
/// for an app factory.
/// This low-level entry point grants trusted-local access to all exposed native
/// actions. Calling this function is the application's automation opt-in.
pub fn serve_stdio(factory: AppFactory) -> crate::Result<()>;

/// Serve live MCP automation for a running canopy app over a Unix-domain
/// socket.
/// This low-level entry point grants trusted-local access. The application must
/// choose a private socket directory and enforce suitable host filesystem
/// permissions.
pub fn serve_uds(
    socket_path: impl AsRef<Path>,
    automation: AutomationHandle,
    metadata: AppMetadata,
) -> crate::Result<UdsServerHandle>;
