// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_examples {
    //! Example widgets used by canopy demos.

    pub mod chargym {
        //! Char gym example nodes.
        //! Chargym: A Unicode width and wide character demo.

        /// Root node for the chargym demo.
        pub struct CharGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the chargym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CharGym {
            /// Construct a new chargym demo.
            pub fn new() -> Self {}
        }

        impl Default for CharGym {
            fn default() -> Self {}
        }

        impl Loader for CharGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for CharGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod editorgym {
        //! Editor gym example nodes.

        /// Root widget for the editor gym demo.
        pub struct EditorGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the editor gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CommandNode for EditorGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for EditorGym {
            fn default() -> Self {}
        }

        impl EditorGym {
            /// Construct a new editor gym demo.
            pub fn new() -> Self {}

            /// Page the outer pane. Negative values move up; positive values move down.
            /// @param delta Signed page delta.
            pub fn page(&mut self, c: &mut dyn Context, delta: i32) {}

            /// Scroll the outer pane by one line in the specified direction.
            /// @param dir The direction to scroll.
            pub fn scroll(&mut self, c: &mut dyn Context, dir: geom::Direction) {}

            /// Scroll the outer pane to an absolute content position.
            pub fn scroll_to(&mut self, c: &mut dyn Context, x: u32, y: u32) {}

            /// Build a positional call with typed user arguments.
            pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll(dir: geom::Direction) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll_to(x: u32, y: u32) -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll_to() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for EditorGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for EditorGym {
            fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod focusgym {
        //! Focus gym example nodes.

        /// A focusable block that can split into children.
        pub struct Block {}

        /// Root node for the focus gym demo.
        pub struct FocusGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the focus gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl Block {
            /// Build a positional call with typed user arguments.
            pub fn call_add() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_flex_grow_dec() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_flex_grow_inc() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_focus() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_split() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_add() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_flex_grow_dec() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_flex_grow_inc() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_focus() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_split() -> &'static canopy::commands::CommandSpec {}
        }

        impl CommandNode for Block {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Widget for Block {
            fn accept_focus(&self, ctx: &dyn ViewContext) -> bool {}

            fn layout(&self) -> Layout {}

            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl CommandNode for FocusGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for FocusGym {
            fn default() -> FocusGym {}
        }

        impl FocusGym {
            /// Construct a new focus gym.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_focused() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_focused() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for FocusGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for FocusGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod fontgym {
        //! Font gym example nodes.

        /// Demo node that renders ASCII font banners.
        pub struct FontGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for focus navigation.
        pub fn setup_bindings(c: &mut canopy::Canopy) -> canopy::error::Result<()> {}

        impl Default for FontGym {
            fn default() -> Self {}
        }

        impl FontGym {
            /// Construct a new font gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for FontGym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }
    }

    pub mod framegym {
        //! Frame gym example nodes.

        /// Root node for the frame gym demo.
        pub struct FrameGym;

        /// A widget that renders a test pattern.
        pub struct TestPattern {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the frame gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CommandNode for TestPattern {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for TestPattern {
            fn default() -> Self {}
        }

        impl TestPattern {
            /// Construct the test pattern node.
            pub fn new() -> Self {}

            /// Page the view. Negative values move up; positive values move down.
            /// @param delta Signed page delta.
            pub fn page(&mut self, c: &mut dyn Context, delta: i32) {}

            /// Scroll by one line in the specified direction.
            /// @param dir The direction to scroll.
            pub fn scroll(&mut self, c: &mut dyn Context, dir: Direction) {}

            /// Scroll to an absolute content position.
            pub fn scroll_to(&mut self, c: &mut dyn Context, x: u32, y: u32) {}

            /// Build a positional call with typed user arguments.
            pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll(dir: Direction) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_scroll_to(x: u32, y: u32) -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_scroll_to() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for TestPattern {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, _view: Size, _ctx: &CanvasContext<'_>) -> Size {}

            fn layout(&self) -> Layout {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl Default for FrameGym {
            fn default() -> Self {}
        }

        impl FrameGym {
            /// Construct a new frame gym.
            pub fn new() -> Self {}
        }

        impl Loader for FrameGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for FrameGym {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod imgview {
        //! Image viewer example nodes.

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Configure key bindings for the image viewer.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}
    }

    pub mod intervals {
        //! Intervals example nodes.

        /// Counter widget that increments on a timer.
        pub struct CounterItem {}

        /// Root node for the intervals demo.
        pub struct Intervals;

        /// Status bar widget for the intervals demo.
        pub struct StatusBar;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the intervals demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CommandNode for Intervals {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for Intervals {
            fn default() -> Self {}
        }

        impl Intervals {
            /// Append a new list item.
            pub fn add_item(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Construct a new intervals demo.
            pub fn new() -> Self {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_item() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_item() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for Intervals {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for Intervals {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, c: &mut dyn Context) -> Option<Duration> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl CounterItem {
            /// Construct a new counter item.
            pub fn new() -> Self {}

            /// Increment the counter.
            pub fn tick(&mut self, ctx: &mut dyn Context) -> Result<()> {}
        }

        impl Default for CounterItem {
            fn default() -> Self {}
        }

        impl Selectable for CounterItem {
            fn set_selected(&mut self, selected: bool) {}
        }

        impl Widget for CounterItem {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn layout(&self) -> Layout {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, rndr: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl Widget for StatusBar {
            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod listgym {
        //! List gym example nodes.

        /// Focusable list entry that renders text content.
        pub struct ListEntry {}

        /// Root node for the list gym demo.
        pub struct ListGym;

        /// Status bar widget for the list gym demo.
        pub struct StatusBar;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the list gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CommandNode for ListGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for ListGym {
            fn default() -> Self {}
        }

        impl ListGym {
            /// Add a new column containing a list.
            pub fn add_column(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Add an item after the current focus.
            pub fn add_item(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Add an item at the end of the list.
            pub fn append_item(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Clear all items from the list.
            pub fn clear(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Construct a new list gym demo.
            pub fn new() -> Self {}

            /// Delete the focused column.
            pub fn delete_column(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_column() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_add_item() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_append_item() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_clear() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_column() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_column() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_add_item() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_append_item() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_column() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for ListGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for ListGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }

        impl Default for StatusBar {
            fn default() -> Self {}
        }

        impl StatusBar {
            /// Construct a status bar.
            pub fn new() -> Self {}
        }

        impl Widget for StatusBar {
            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl ListEntry {
            /// Construct a new list entry from a text widget.
            pub fn new(text: Text) -> Self {}
        }

        impl Selectable for ListEntry {
            fn set_selected(&mut self, selected: bool) {}
        }

        impl Widget for ListEntry {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod pager {
        //! Pager example nodes.

        /// Simple pager widget for file contents.
        pub struct Pager {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the pager demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl Loader for Pager {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Pager {
            /// Construct a pager with initial contents.
            pub fn new(contents: &str) -> Self {}
        }

        impl Widget for Pager {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod stylegym {
        //! Stylegym example nodes.
        //! Stylegym: A demonstration app for Canopy's styling features.
        //!
        //! This example showcases themes, effects, and modal overlays in a two-pane
        //! layout.

        /// The demo content pane showing styled samples.
        pub struct DemoContent;

        /// Effect option for the selector.
        pub struct EffectOption {
            /// Effect display name.
            pub name: &'static str,
            /// Style effect applied when this option is selected.
            pub effect: canopy::style::effects::Effect,
        }

        /// Root widget for the stylegym demo.
        pub struct Stylegym {}

        /// Theme option for the dropdown.
        pub struct ThemeOption {
            /// Theme display name.
            pub name: &'static str,
            /// Function to build the theme's StyleMap.
            pub builder: fn() -> canopy::style::StyleMap,
        }

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Set up key bindings for the stylegym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl Clone for EffectOption {
            fn clone(&self) -> EffectOption {}
        }

        impl Label for EffectOption {
            fn label(&self) -> &str {}
        }

        impl Clone for ThemeOption {
            fn clone(&self) -> ThemeOption {}
        }

        impl Label for ThemeOption {
            fn label(&self) -> &str {}
        }

        impl CommandNode for Stylegym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for Stylegym {
            fn default() -> Self {}
        }

        impl Loader for Stylegym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Stylegym {
            /// Apply the selected effects from the selector to the demo pane.
            pub fn apply_effects(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Apply the selected theme from the dropdown.
            pub fn apply_theme(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Create a new stylegym instance.
            pub fn new() -> Self {}

            /// Hide the modal overlay.
            pub fn hide_modal(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Show the modal overlay.
            pub fn show_modal(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_apply_effects() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_apply_theme() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_hide_modal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_show_modal() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_apply_effects() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_apply_theme() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_hide_modal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_show_modal() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for Stylegym {
            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }

        impl Widget for DemoContent {
            fn layout(&self) -> Layout {}

            fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod termgym {
        //! Terminal gym example nodes.

        /// Multi-terminal demo widget.
        pub struct TermGym {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings and styles for the terminal gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl CommandNode for TermGym {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for TermGym {
            fn default() -> Self {}
        }

        impl Loader for TermGym {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl TermGym {
            /// Activate a terminal from a sidebar row selection.
            pub fn activate_terminal(&mut self, c: &mut dyn Context, index: usize) -> Result<()> {}

            /// Close the active terminal and keep focus on the sidebar.
            pub fn delete_terminal(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Construct the terminal gym demo.
            pub fn new() -> Self {}

            /// Create a new terminal instance while keeping focus on the sidebar.
            pub fn new_terminal_sidebar(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Create a new terminal instance.
            pub fn new_terminal(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Focus the active terminal instance.
            pub fn focus_active_terminal(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Switch to the next terminal while keeping focus on the sidebar.
            pub fn next_terminal_sidebar(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Switch to the previous terminal while keeping focus on the sidebar.
            pub fn prev_terminal_sidebar(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Toggle focus between the terminal list and the active terminal.
            pub fn toggle_terminal_focus(&mut self, c: &mut dyn Context) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_activate_terminal(index: usize) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_delete_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_focus_active_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_new_terminal() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_new_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_next_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_prev_terminal_sidebar() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_toggle_terminal_focus() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_activate_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_delete_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_focus_active_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_new_terminal() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_new_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_next_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_prev_terminal_sidebar() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_toggle_terminal_focus() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for TermGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn layout(&self) -> Layout {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, r: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }
    }

    pub mod textgym {
        //! Text gym example nodes.

        /// Demo node that displays multiple text variants.
        pub struct TextGym;

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Install key bindings for the text gym demo.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl Default for TextGym {
            fn default() -> Self {}
        }

        impl TextGym {
            /// Construct a new text gym demo.
            pub fn new() -> Self {}
        }

        impl Widget for TextGym {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }
    }

    pub mod widget {
        //! Widget demo nodes.
        //! Widget demo entry points.

        /// Host widget that centers a padded child within optional sizing overrides.
        pub struct DemoHost {}

        /// Common sizing configuration for widget demos.
        pub struct DemoSize {
            /// Optional fixed width override.
            pub width: Option<u32>,
            /// Optional fixed height override.
            pub height: Option<u32>,
        }

        /// Font widget configuration.
        pub struct FontDemo {}

        /// Font source data for demo cycling.
        pub struct FontSource {}

        /// List widget configuration.
        pub struct ListDemo {}

        /// Terminal demo widget with three commands.
        pub struct TermDemo {}

        impl Clone for DemoSize {
            fn clone(&self) -> DemoSize {}
        }

        impl Debug for DemoSize {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Default for DemoSize {
            fn default() -> DemoSize {}
        }

        impl DemoSize {
            /// Create sizing overrides.
            pub fn new(width: Option<u32>, height: Option<u32>) -> Self {}
        }

        impl Clone for FontSource {
            fn clone(&self) -> FontSource {}
        }

        impl Debug for FontSource {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl FontSource {
            /// Build a font source from raw bytes.
            pub fn new(label: impl Into<String>, bytes: Vec<u8>) -> Self {}
        }

        impl CommandNode for TermDemo {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Default for TermDemo {
            fn default() -> Self {}
        }

        impl TermDemo {
            /// Construct a terminal demo.
            pub fn new() -> Self {}

            /// Cycle to the next tab.
            pub fn next_tab(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_next_tab() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_next_tab() -> &'static canopy::commands::CommandSpec {}
        }

        impl Widget for TermDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn render(&mut self, rndr: &mut Render<'_>, _ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl DemoHost {
            /// Build a demo host for the provided widget.
            pub fn new(child: impl Into<Box<dyn Widget>>, size: DemoSize, frame: bool) -> Self {}

            /// Set the inner padding for the demo host.
            pub fn with_inner_padding(self, padding: u32) -> Self {}

            /// Set the outer padding for the demo host.
            pub fn with_outer_padding(self, padding: u32) -> Self {}
        }

        impl Widget for DemoHost {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}
        }

        impl FontDemo {
            /// Build a font demo widget.
            pub fn new(
                text: impl Into<String>,
                fonts: Vec<FontSource>,
                interval: Duration,
                exit_after_cycle: bool,
                effects: FontEffects,
            ) -> Self {
            }
        }

        impl Widget for FontDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }

        impl ListDemo {
            /// Build a list demo widget.
            pub fn new(interval: Duration) -> Self {}

            /// Return the width and height that exactly fit the demo's items.
            pub fn natural_size() -> (u32, u32) {}
        }

        impl Widget for ListDemo {
            fn layout(&self) -> Layout {}

            fn name(&self) -> NodeName {}

            fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, ctx: &mut dyn Context) -> Option<Duration> {}
        }
    }

    pub mod widget_editor {
        //! Widget editor example nodes.

        /// Widget editor example that opens a Rust file with syntax highlighting.
        pub struct WidgetEditor {}

        #[must_use]
        /// Queue this demo's bindings and native configuration in their builder phases.
        pub fn binding_setup(builder: canopy::CanopyBuilder) -> canopy::CanopyBuilder {}

        /// Return a lowercase file extension hint for syntax selection.
        pub fn file_extension(path: &std::path::Path) -> String {}

        /// Return a short title for the editor frame.
        pub fn file_title(path: &std::path::Path) -> String {}

        /// Install key bindings for the widget editor example.
        pub fn setup_bindings(cnpy: &mut Canopy) -> Result<()> {}

        impl Loader for WidgetEditor {
            fn load(c: &mut Canopy) -> Result<()> {}
        }

        impl Widget for WidgetEditor {
            fn on_mount(&mut self, c: &mut dyn Context) -> Result<()> {}
        }

        impl WidgetEditor {
            /// Construct a widget editor from file contents and metadata.
            pub fn new(
                contents: impl Into<String>,
                extension: impl Into<String>,
                title: impl Into<String>,
            ) -> Self {
            }
        }
    }

    #[must_use]
    /// Start demo registration with Root and its first-preparation help setup.
    pub fn demo_canopy() -> canopy::CanopyBuilder {}

    /// Finalize and print the Luau API definitions for a demo app.
    pub fn print_luau_api(cnpy: &mut canopy::Canopy) -> canopy::error::Result<()> {}

    /// Install one demo app under a root and run the terminal loop.
    pub fn run_demo<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
    ) -> canopy::error::Result<i32> {
    }

    /// Install a demo and run it with explicit terminal interrupt behavior.
    pub fn run_demo_with_options<T: 'static + Widget>(
        builder: canopy::CanopyBuilder,
        app: T,
        inspector: bool,
        options: canopy::terminal::RunOptions,
    ) -> canopy::error::Result<i32> {
    }

    /// Render the shared scroll bindings for one receiver and binding path.
    pub fn text_scroll_bindings(receiver: &str, path: &str) -> String {}
}
