// @generated by `ruskel-snapshot`; do not edit.

pub mod canopy_widgets {
    //! Built-in widgets for canopy applications.
    //!
    //! This crate provides a collection of reusable widgets for building terminal
    //! user interfaces with canopy.

    #[expect(
        clippy::multiple_inherent_impl,
        reason = "Editor methods are split by rendering, vi, and prompt concerns."
    )]
    pub mod editor {
        //! Editor widget and supporting types.

        pub mod highlight {
            //! Syntax highlighting helpers.
            //!
            //! [`SyntectHighlighter`] resolves a syntax from a file name or from the text
            //! itself, then highlights lines incrementally. Highlighting a line needs the
            //! parser state left by every line above it, so the highlighter walks forward
            //! from the last line it has seen and caches the spans it produces. A source
            //! set through [`Highlighter::prepare`] therefore costs only the lines that are
            //! actually asked for, and multi-line constructs such as block comments keep
            //! their state.

            /// A highlighted span for a single line.
            #[derive(Clone, Debug)]
            pub struct HighlightSpan {
                /// Character range covered by the span.
                pub range: std::ops::Range<usize>,
                /// Style to apply to the span.
                pub style: canopy::style::Style,
            }

            /// A syntect-backed highlighter.
            ///
            /// Language detection uses the file name or extension, then the first source
            /// line. Parser state is retained for at most 4,000 lines; later lines
            /// highlight independently.
            #[derive(Debug)]
            pub struct SyntectHighlighter {}

            /// Trait for providing syntax highlighting spans.
            pub trait Highlighter {
                /// Return highlight spans for a line of text.
                fn highlight_line(&self, line: usize, text: &str) -> Vec<HighlightSpan>;

                /// Adopt `text` as the source being highlighted, discarding earlier state.
                ///
                /// Highlighters that carry parser state between lines need the whole
                /// source. The default implementation ignores it.
                /// The editor calls this during rendering, before requesting spans, when
                /// its source or highlighter has changed.
                fn prepare(&self, text: &str) {}
            }

            /// Theme used when the caller names none, matching the Canopy style theme.
            pub const DEFAULT_THEME: &str = "Canopy (dark)";

            impl Highlighter for SyntectHighlighter {
                fn highlight_line(&self, line: usize, text: &str) -> Vec<HighlightSpan> {}

                fn prepare(&self, text: &str) {}
            }

            impl SyntectHighlighter {
                #[must_use]
                /// Construct a highlighter for the file at `path`.
                pub fn for_path(path: impl AsRef<Path>) -> Self {}

                #[must_use]
                /// Construct a highlighter for the provided file extension.
                pub fn new(extension: impl AsRef<str>) -> Self {}

                #[must_use]
                /// Return the name of the syntax in use.
                pub fn syntax_name(&self) -> String {}

                #[must_use]
                /// Use the named theme, falling back to [`DEFAULT_THEME`].
                pub fn with_theme(self, name: impl AsRef<str>) -> Self {}

                /// Select the syntax for `extension`, discarding any prepared source.
                pub fn set_extension(&self, extension: &str) {}

                /// Select the syntax for `path`, discarding any prepared source.
                ///
                /// A file name is tried first, so `Makefile` and `Dockerfile` resolve, then
                /// the extension.
                pub fn set_path(&self, path: impl AsRef<Path>) {}
            }
        }

        /// Editing mode for the editor widget.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum EditMode {
            /// Text entry mode with direct insertion.
            Text,
            /// Vi-style modal editing.
            Vi,
        }

        /// Editor widget implementation.
        pub struct Editor {}

        /// Configuration for the editor widget.
        #[derive(Clone, Debug, Default)]
        pub struct EditorConfig {
            /// Allow multi-line content.
            pub multiline: bool,
            /// Wrapping mode.
            pub wrap: WrapMode,
            /// Auto-grow height to fit contents.
            pub auto_grow: bool,
            /// Minimum height when auto-growing.
            pub min_height: u32,
            /// Maximum height when auto-growing.
            pub max_height: Option<u32>,
            /// Edit mode behavior.
            pub mode: EditMode,
            /// Whether the editor is read-only.
            pub read_only: bool,
            /// Whether the editor accepts focus.
            pub focusable: bool,
            /// Line number rendering mode.
            pub line_numbers: LineNumbers,
            /// Tab stop width in columns.
            pub tab_stop: usize,
        }

        /// Line number rendering mode.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum LineNumbers {
            /// Do not render line numbers.
            None,
            /// Render absolute line numbers.
            Absolute,
            /// Render relative line numbers (current line stays absolute).
            Relative,
        }

        /// Wrapping behavior for the editor.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum WrapMode {
            /// No wrapping; horizontal scrolling is enabled.
            None,
            /// Soft wrapping at the view width.
            Soft,
        }

        impl CommandNode for Editor {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Widget for Editor {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}

            fn cursor(&self) -> Option<cursor::Cursor> {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

            fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

            fn reveal_anchor(&self, view: Size) -> Option<Rect> {}
        }

        impl super::widget::Editor {
            /// Construct an editor with a configuration.
            pub fn with_config(text: impl Into<String>, config: EditorConfig) -> Self {}

            /// Install a syntax highlighter.
            ///
            /// Preparation is deferred until the next render, using the latest buffer
            /// contents. Repeated changes before rendering prepare only the final
            /// state.
            pub fn set_highlighter(&mut self, highlighter: Option<Box<dyn Highlighter>>) {}

            /// Make another search match current and scroll to it.
            /// @param delta Matches to move; negative values move backward.
            pub fn search_next(&mut self, ctx: &mut dyn Context, delta: i32) {}

            /// Move the cursor.
            /// @param dir The direction to move the cursor.
            pub fn move_cursor(&mut self, ctx: &mut dyn Context, dir: FocusDirection) {}

            /// Redo the last undone edit.
            pub fn redo(&mut self, _ctx: &mut dyn Context) {}

            /// Remove the search and its highlights.
            pub fn clear_search(&mut self, _ctx: &mut dyn Context) {}

            /// Replace the buffer contents.
            pub fn set_text(&mut self, text: impl Into<String>) {}

            /// Replace the editor configuration.
            pub fn set_config(&mut self, config: EditorConfig) {}

            /// Return the buffer contents.
            pub fn text(&self) -> String {}

            /// Return the current editor configuration.
            pub fn config(&self) -> &EditorConfig {}

            /// Return the number of search matches.
            pub fn search_matches(&self) -> usize {}

            /// Return the one-based position of the current search match.
            /// @return The position, or 0 when there is no current match.
            pub fn search_position(&self) -> usize {}

            /// Search the text and highlight every match.
            ///
            /// The first match at or below the top of the view becomes current, and
            /// the view scrolls to it. A query without uppercase letters ignores ASCII
            /// case. An empty query clears the search.
            /// @param query Text to find.
            pub fn search(&mut self, ctx: &mut dyn Context, query: String) {}

            /// Undo the last edit.
            pub fn undo(&mut self, _ctx: &mut dyn Context) {}

            /// Build a positional call with typed user arguments.
            pub fn call_clear_search() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_move_cursor(dir: FocusDirection) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_redo() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_search(query: String) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_search_matches() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_search_next(delta: i32) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_search_position() -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_undo() -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_clear_search() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_move_cursor() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_redo() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_search() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_search_matches() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_search_next() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_search_position() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_undo() -> &'static canopy::commands::CommandSpec {}
        }

        impl EditorConfig {
            /// Configure auto-grow behavior.
            pub fn with_auto_grow(self, auto_grow: bool) -> Self {}

            /// Configure line number rendering.
            pub fn with_line_numbers(self, line_numbers: LineNumbers) -> Self {}

            /// Configure multiline behavior.
            pub fn with_multiline(self, multiline: bool) -> Self {}

            /// Configure read-only behavior.
            pub fn with_read_only(self, read_only: bool) -> Self {}

            /// Configure the edit mode.
            pub fn with_mode(self, mode: EditMode) -> Self {}

            /// Configure the maximum height.
            pub fn with_max_height(self, max_height: Option<u32>) -> Self {}

            /// Configure the minimum height.
            pub fn with_min_height(self, min_height: u32) -> Self {}

            /// Configure the tab stop width.
            pub fn with_tab_stop(self, tab_stop: usize) -> Self {}

            /// Configure whether the editor accepts focus.
            ///
            /// A read-only view embedded for display alone should decline focus so
            /// that focus traversal skips over it.
            pub fn with_focusable(self, focusable: bool) -> Self {}

            /// Configure wrapping mode.
            pub fn with_wrap(self, wrap: WrapMode) -> Self {}

            /// Construct a default editor configuration.
            pub fn new() -> Self {}
        }
    }

    pub mod font {
        //! ASCII font rasterization helpers.

        /// Rasterized font data for terminal rendering.
        #[derive(Clone)]
        pub struct Font {}

        /// Render large ASCII-font text into a bounded region.
        pub struct FontBanner {}

        /// Rendering effects applied to font output.
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct FontEffects {
            /// Thicken strokes by adding extra coverage.
            pub bold: bool,
            /// Slant glyphs to the right.
            pub italic: bool,
            /// Draw an underline through the glyphs.
            pub underline: bool,
            /// Reduce contrast by dimming coverage.
            pub dim: bool,
            /// Draw an overline through the glyphs.
            pub overline: bool,
            /// Draw a strike-through line through the glyphs.
            pub strike: bool,
        }

        /// Renderer that converts fonts into terminal text.
        pub struct FontRenderer {}

        /// Widget that renders an image into terminal cells.
        pub struct ImageView {}

        /// Alignment configuration for font layouts.
        #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
        pub struct LayoutOptions {
            /// Horizontal alignment within the target canvas.
            pub h_align: canopy::layout::Align,
            /// Vertical alignment within the target canvas.
            pub v_align: canopy::layout::Align,
        }

        impl CommandNode for ImageView {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl ImageView {
            #[must_use]
            /// Create an image view with nothing to show yet.
            ///
            /// The view holds a single transparent pixel until [`Self::set_image`] or
            /// [`Self::set_path`] gives it real content. Callers that mount a viewer
            /// before they have an image should keep it hidden until then.
            pub fn empty() -> Self {}

            /// Create a new image view widget from a file path.
            pub fn from_path(path: impl AsRef<Path>) -> Result<Self> {}

            /// Create a new image view widget.
            pub fn new(image: &RgbaImage) -> Self {}

            /// Load a thumbnail within `bounds`, preserving its aspect ratio.
            ///
            /// Small images keep their original pixels. Larger images are averaged
            /// after compositing transparency onto black. Zooming uses the thumbnail;
            /// use [`Self::set_path`] to retain full-resolution zooming instead.
            ///
            /// The source is limited to 32 * 1024 * 1024 pixels and the decoder has a
            /// 128 MiB allocation budget. Conversion can allocate one additional RGBA
            /// source buffer. Each thumbnail edge is capped at 1024 pixels, even when
            /// `bounds` is larger. Sampling tables use at most 24 * (width + 1) *
            /// (height + 1) bytes for the thumbnail dimensions. Zero bounds are
            /// invalid. On failure, the current image is preserved. Callers should
            /// also bound the encoded file size.
            pub fn set_preview_path(&mut self, path: impl AsRef<Path>, bounds: Size) -> Result<()> {
            }

            /// Pan by one step in the specified direction.
            /// @param dir The pan direction.
            pub fn pan(&mut self, ctx: &mut dyn Context, dir: FocusDirection) -> Result<()> {}

            /// Show a different image, returning the view to its auto-fitted state.
            pub fn set_image(&mut self, image: &RgbaImage) {}

            /// Show the image at `path`, returning the view to its auto-fitted state.
            ///
            /// The view keeps its current image when the file cannot be read.
            pub fn set_path(&mut self, path: impl AsRef<Path>) -> Result<()> {}

            /// Zoom around the view center.
            /// @param dir The zoom direction.
            pub fn zoom(&mut self, ctx: &mut dyn Context, dir: ZoomDirection) -> Result<()> {}

            /// Build a positional call with typed user arguments.
            pub fn call_pan(dir: FocusDirection) -> canopy::commands::CommandCall {}

            /// Build a positional call with typed user arguments.
            pub fn call_zoom(dir: ZoomDirection) -> canopy::commands::CommandCall {}

            /// Return a typed command reference for this command.
            pub fn cmd_pan() -> &'static canopy::commands::CommandSpec {}

            /// Return a typed command reference for this command.
            pub fn cmd_zoom() -> &'static canopy::commands::CommandSpec {}
        }

        impl Loader for ImageView {
            /// Register commands for the image viewer widget.
            fn load(cnpy: &mut Canopy) -> Result<()> {}
        }

        impl Widget for ImageView {
            /// Accept focus so key bindings apply to this widget.
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            /// Fill the available space in the terminal view.
            fn layout(&self) -> Layout {}

            /// Render the current image view into the terminal buffer.
            fn render(&mut self, render: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}
        }

        impl Font {
            /// Load a font from in-memory bytes.
            pub fn from_bytes(data: impl AsRef<[u8]>) -> Result<Self> {}

            /// Return the font name, if provided in metadata.
            pub fn name(&self) -> Option<&str> {}
        }

        impl FontBanner {
            /// Configure layout options for the banner.
            pub fn with_layout_options(self, options: LayoutOptions) -> Self {}

            /// Configure rendering effects for the banner.
            pub fn with_effects(self, effects: FontEffects) -> Self {}

            /// Configure the banner style path.
            pub fn with_style(self, style: impl Into<String>) -> Self {}

            /// Construct a banner with text and a renderer.
            pub fn new(text: impl Into<String>, renderer: FontRenderer) -> Self {}

            /// Update rendering effects for the banner.
            pub fn set_effects(&mut self, effects: FontEffects) {}

            /// Update the banner renderer.
            pub fn set_renderer(&mut self, renderer: FontRenderer) {}

            /// Update the banner text.
            pub fn set_text(&mut self, text: impl Into<String>) {}
        }

        impl Widget for FontBanner {
            fn layout(&self) -> Layout {}

            fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl FontRenderer {
            /// Create a renderer for the provided font.
            pub fn new(font: Font) -> Self {}
        }
    }

    pub mod scrollbar {
        //! Proportional scrollbars and the nodes they display.
        //!
        //! A scrollbar owner, such as [`crate::Frame`], draws the scroll position of a
        //! node beneath it. [`scroll_target`] finds that node for one axis. A
        //! [`Scrollbar`] draws the node's thumb into a track in the owner's outer
        //! coordinates and turns pointer input on the track into scrolling. Wheel
        //! input on a track scrolls the node. A press on the track centers the thumb on
        //! the pointer, and a drag keeps the thumb under the pointer.

        /// The axis a scrollbar measures.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub enum Axis {
            /// Rows, with a track that runs top to bottom.
            Vertical,
            /// Columns, with a track that runs left to right.
            Horizontal,
        }

        /// A node whose canvas overflows its content along one axis.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub struct ScrollTarget {
            /// Node whose view scrolls.
            pub node: canopy::NodeId,
            /// The node's content viewport in screen coordinates, clipped by the
            /// content of every ancestor and by the screen.
            pub viewport: canopy::geom::Rect,
        }

        /// A proportional scrollbar for one axis.
        ///
        /// The owner resolves its tracks before each render and event, and passes each
        /// track with the node it scrolls. A drag stays bound to the node and track it
        /// started on. It ends when either changes, or when another node takes mouse
        /// capture.
        #[derive(Clone, Copy, Debug)]
        pub struct Scrollbar {}

        /// Return the one node beneath `owner` whose canvas overflows along `axis`.
        ///
        /// The search skips nodes with no visible content, which includes hidden
        /// nodes. It does not descend into a node that overflows or into a widget that
        /// owns scrollbars. It returns `None` when no node qualifies, when more than
        /// one does, or when `owner` is detached. The owner's own widget is never
        /// read, so an owner can call this while it renders or handles an event.
        pub fn scroll_target(
            ctx: &dyn ViewContext,
            owner: canopy::NodeId,
            axis: Axis,
        ) -> canopy::error::Result<Option<ScrollTarget>> {
        }

        impl Scrollbar {
            #[must_use]
            /// Also draw the track around the thumb with `style` and `glyph`.
            pub const fn with_track(self, style: &'static str, glyph: char) -> Self {}

            #[must_use]
            /// Draw the thumb with `style` while a drag holds it.
            pub const fn with_active(self, style: &'static str) -> Self {}

            /// Construct a horizontal scrollbar whose thumb uses `style` and `glyph`.
            pub const fn horizontal(style: &'static str, glyph: char) -> Self {}

            /// Construct a vertical scrollbar whose thumb uses `style` and `glyph`.
            pub const fn vertical(style: &'static str, glyph: char) -> Self {}

            /// Draw the thumb of each track's node.
            ///
            /// `tracks` pairs each node with its track, in the outer coordinates of
            /// the context's node. A node that shows its whole canvas draws nothing.
            /// Rendering cannot release mouse capture, so a drag whose node or track
            /// has changed draws no active thumb and ends at the next event.
            pub fn render(
                &mut self,
                render: &mut Render<'_>,
                ctx: &dyn ViewContext,
                tracks: &[(NodeId, Rect)],
            ) -> Result<()> {
            }

            /// Handle a mouse event for the scrollbars drawn in `tracks`.
            ///
            /// `tracks` holds the tracks resolved for this event, as passed to
            /// [`Scrollbar::render`]. A press on a track captures the mouse for the
            /// context's node and the release frees it. Returns
            /// [`EventOutcome::Handle`] for events the scrollbar uses.
            pub fn handle_mouse(
                &mut self,
                ctx: &mut dyn Context,
                event: &mouse::MouseEvent,
                tracks: &[(NodeId, Rect)],
            ) -> Result<EventOutcome> {
            }
        }
    }

    pub mod terminal {
        //! Terminal emulation widget.

        /// Terminal widget backed by `itty`.
        pub struct Terminal {}

        /// Terminal widget configuration.
        #[derive(Default)]
        pub struct TerminalConfig {}

        impl CommandNode for Terminal {
            fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
        }

        impl Terminal {
            /// Construct a new terminal widget with the provided configuration.
            pub fn new(config: TerminalConfig) -> Self {}
        }

        impl Widget for Terminal {
            fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

            fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}

            fn cursor(&self) -> Option<cursor::Cursor> {}

            fn measure(&self, c: MeasureConstraints) -> Measurement {}

            fn name(&self) -> NodeName {}

            fn on_event(
                &mut self,
                event: &event::Event,
                ctx: &mut dyn Context,
            ) -> Result<EventOutcome> {
            }

            fn on_mount(&mut self, _ctx: &mut dyn Context) -> Result<()> {}

            fn poll(&mut self, _ctx: &mut dyn Context) -> Option<Duration> {}

            fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
        }

        impl TerminalConfig {
            /// Configure the command argv to run instead of the default shell.
            pub fn with_command<I, S>(self, command: I) -> Self
            where
                I: IntoIterator<Item = S>,
                S: Into<String>, {
            }

            /// Configure the working directory for the terminal process.
            pub fn with_cwd(self, cwd: impl Into<PathBuf>) -> Self {}

            /// Construct a default terminal configuration.
            pub fn new() -> Self {}
        }
    }

    pub mod text_buffer {
        //! Shared text editing machinery for Input and Editor.
        //! Feature-independent rope storage, editing, and selection helpers.

        /// A text selection expressed as an anchor and head position.
        #[derive(Clone, Copy, Debug, Eq, PartialEq)]
        pub struct Selection {}

        /// Rope-backed text buffer with selection and undo/redo support.
        #[derive(Clone, Debug)]
        pub struct TextBuffer {}

        /// A position in the text buffer expressed as a logical line and a char index.
        #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        pub struct TextPosition {
            /// Logical line index (0-based).
            pub line: usize,
            /// Char index within the line (0-based).
            pub column: usize,
        }

        /// A half-open text range expressed in buffer coordinates.
        #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
        pub struct TextRange {
            /// Range start position (inclusive).
            pub start: TextPosition,
            /// Range end position (exclusive).
            pub end: TextPosition,
        }

        /// Scoped text edit transaction.
        pub struct TextTransaction<'a> {}

        impl Deref for TextTransaction<'_> {
            fn deref(&self) -> &Self::Target {}

            type Target = TextBuffer;
        }

        impl DerefMut for TextTransaction<'_> {
            fn deref_mut(&mut self) -> &mut Self::Target {}
        }

        impl Drop for TextTransaction<'_> {
            fn drop(&mut self) {}
        }

        impl Selection {
            /// Construct a collapsed selection at a position.
            pub fn caret(position: TextPosition) -> Self {}

            /// Construct a selection from anchor and head positions.
            pub fn new(anchor: TextPosition, head: TextPosition) -> Self {}

            /// Return the anchor position.
            pub fn anchor(self) -> TextPosition {}

            /// Return the head position.
            pub fn head(self) -> TextPosition {}

            /// Return the selection range as a normalized text range.
            pub fn range(self) -> TextRange {}

            /// Return true if the selection is empty.
            pub fn is_empty(self) -> bool {}

            /// Update the head position.
            pub fn set_head(&mut self, head: TextPosition) {}
        }

        impl TextBuffer {
            /// Begin a grouped transaction that commits when the guard is dropped.
            pub fn transaction(&mut self) -> TextTransaction<'_> {}

            /// Begin a grouped transaction.
            pub fn begin_transaction(&mut self) {}

            /// Commit the active transaction, if any.
            pub fn commit_transaction(&mut self) {}

            /// Create a new buffer from an initial string.
            pub fn new(text: impl Into<String>) -> Self {}

            /// Delete the selection or the grapheme after the cursor.
            pub fn delete_forward(&mut self, allow_line_wrap: bool) -> bool {}

            /// Delete the selection or the grapheme before the cursor.
            pub fn delete_backward(&mut self, allow_line_wrap: bool) -> bool {}

            /// Insert text at the cursor, replacing any selection.
            pub fn insert_text(&mut self, text: &str) {}

            /// Move the cursor left by one grapheme.
            pub fn move_left(&mut self, allow_line_wrap: bool) -> bool {}

            /// Move the cursor right by one grapheme.
            pub fn move_right(&mut self, allow_line_wrap: bool) -> bool {}

            /// Move the cursor to the end of the current line.
            pub fn move_line_end(&mut self) {}

            /// Move the cursor to the first non-whitespace character in the line.
            pub fn move_line_first_non_ws(&mut self) {}

            /// Move the cursor to the start of the current line.
            pub fn move_line_start(&mut self) {}

            /// Redo the most recently undone transaction.
            pub fn redo(&mut self) -> bool {}

            /// Replace a range with the provided text.
            pub fn replace_range(&mut self, range: TextRange, text: &str) {}

            /// Replace the cursor and collapse the selection.
            pub fn set_cursor(&mut self, pos: TextPosition) {}

            /// Replace the selection, clamping to bounds.
            pub fn set_selection(&mut self, selection: Selection) {}

            /// Return the closest position for a display column within a line.
            pub fn position_for_column(
                &self,
                line: usize,
                column: usize,
                tab_stop: usize,
            ) -> TextPosition {
            }

            /// Return the current buffer revision.
            pub fn revision(&self) -> u64 {}

            /// Return the current selection.
            pub fn selection(&self) -> Selection {}

            /// Return the cursor position (selection head).
            pub fn cursor(&self) -> TextPosition {}

            /// Return the display column for a position.
            pub fn column_for_position(&self, pos: TextPosition, tab_stop: usize) -> usize {}

            /// Return the end position for a line, optionally including the newline.
            pub fn line_end_position(&self, line: usize, include_newline: bool) -> TextPosition {}

            /// Return the full buffer contents as a string.
            pub fn text(&self) -> String {}

            /// Return the line length in chars, excluding any trailing newline.
            pub fn line_char_len(&self, line: usize) -> usize {}

            /// Return the range a forward delete at `from` would remove.
            ///
            /// At the end of a line the range joins the next line when
            /// `allow_line_wrap` is set. Returns `None` when there is nothing after
            /// the position to delete.
            pub fn forward_delete_range(
                &self,
                from: TextPosition,
                allow_line_wrap: bool,
            ) -> Option<TextRange> {
            }

            /// Return the text in a range.
            pub fn range_text(&self, range: TextRange) -> String {}

            /// Return the text of a logical line without a trailing newline.
            pub fn line_text(&self, line: usize) -> String {}

            /// Return the total number of logical lines.
            pub fn line_count(&self) -> usize {}

            /// Undo the most recent transaction.
            pub fn undo(&mut self) -> bool {}
        }

        impl TextPosition {
            /// Create a new text position.
            pub fn new(line: usize, column: usize) -> Self {}
        }

        impl TextRange {
            /// Construct a text range.
            pub fn new(start: TextPosition, end: TextPosition) -> Self {}

            /// Return a range with start/end ordered.
            pub fn normalized(self) -> Self {}

            /// Return true if the range is empty.
            pub fn is_empty(self) -> bool {}
        }
    }

    /// Monotonic key for list items.
    #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
    pub struct AutoKey(_);

    /// A simple box container around its children.
    #[derive(Default)]
    pub struct Border {}

    /// Defines the set of glyphs used to draw the box.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub struct BoxGlyphs {
        /// Top-left corner glyph.
        pub topleft: char,
        /// Top-right corner glyph.
        pub topright: char,
        /// Bottom-left corner glyph.
        pub bottomleft: char,
        /// Bottom-right corner glyph.
        pub bottomright: char,
        /// Horizontal border glyph.
        pub horizontal: char,
        /// Vertical border glyph.
        pub vertical: char,
    }

    /// Button widget that triggers a command when clicked.
    ///
    /// Mouse clicks are consumed without dispatching when the command is disabled.
    /// Calling [`Button::press`] directly still reports command errors.
    pub struct Button {}

    /// Canvas width behavior for text widgets.
    #[derive(Clone, Copy, Debug, Eq, PartialEq)]
    pub enum CanvasWidth {
        /// Match the view width.
        View,
        /// Use the maximum wrapped line width.
        Intrinsic,
        /// Use a fixed canvas width.
        Fixed(u32),
    }

    /// Container that centers its child within available space.
    ///
    /// For a dimmed overlay, push an effect on the background content with
    /// `c.push_effect(background_id, effects::brightness(0.5))`. This container
    /// stays at full brightness because it is a sibling of the dimmed content, not
    /// a descendant. Insert it as a sibling inside a parent that uses `Stack`
    /// layout so it can overlay the existing view.
    #[derive(Default)]
    pub struct Center;

    /// Panes side by side, each followed by a divider.
    ///
    /// Children are panes with normal child sizing. `Columns` places them in a
    /// row, with a one-cell gap after each displayed pane and one trailing column.
    /// That cell holds a divider across the pane's rows. When a node in a pane
    /// overflows vertically and reaches the pane's right edge, the divider beside
    /// the node's visible rows becomes a track that shows and controls its
    /// position; headers and footers in the pane keep plain divider lines. The
    /// trailing column stays blank while the last pane fits. Horizontal overflow
    /// scrolls through wheel input without a track.
    ///
    /// `Columns` owns the scrollbars of its panes, so an enclosing frame draws none
    /// for them. Dividers use `columns/divider`, thumbs `columns/thumb`, and a thumb
    /// a drag holds `columns/thumb/active`.
    #[derive(Default)]
    pub struct Columns {}

    /// A widget that lays out its children and has no other behavior.
    ///
    /// Parents adjust how each child sizes through layout overrides. Use
    /// [`Container::with_name`] to keep a path segment that scripts or bindings
    /// match.
    pub struct Container {}

    /// A dropdown widget for single-value selection.
    ///
    /// When collapsed, displays the currently selected item with a dropdown
    /// indicator. When expanded, displays all options for selection.
    /// Opening and navigation scroll the highlighted row into view after layout.
    pub struct Dropdown<T>
    where
        T: Label, {}

    /// A frame around an element with an optional title and scroll positions.
    ///
    /// A frame owns the scrollbars of its subtree. On each axis it finds the one
    /// node beneath it whose canvas overflows, and draws that node's thumb on the
    /// right or bottom border beside the node's visible rows or columns. The
    /// border carries a track only where that node reaches it, so a sidebar,
    /// header, or footer keeps a plain border. Wheel input, presses, and drags on
    /// a track scroll the node. Thumbs use `frame/thumb`, and
    /// `frame/thumb/active` while a drag holds them.
    #[derive(Default)]
    pub struct Frame {}

    /// Widget that renders an image into terminal cells.
    pub struct ImageView {}

    /// Single-line text input widget.
    pub struct Input {}

    /// A typed list container for widget items.
    ///
    /// List items are actual widgets in the tree, enabling composition and focus
    /// management. The list arranges items vertically and supports scrolling.
    ///
    /// Items must implement the [`Selectable`] trait so the list can manage their
    /// selection state independently of focus.
    #[derive(Default)]
    pub struct List<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue = AutoKey> {}

    /// Container that adds padding around its child.
    pub struct Pad {}

    /// A Root widget that lives at the base of a Canopy app.
    #[derive(Default)]
    pub struct Root {}

    /// A container that lays its children out past its viewport and scrolls over
    /// them.
    ///
    /// Children are ordinary nodes. On a scrolling axis they measure without a
    /// bound, and the canvas spans their allocated rectangles. Content that must
    /// grow along that axis uses measured or fixed sizing; flex children share
    /// only the space that remains. The other axis stays bounded, even inside an
    /// unbounded ancestor.
    ///
    /// `Scroll` accepts no focus and installs no keys. Wheel input scrolls it
    /// through the runtime's default action, focus changes reveal the focused
    /// node, and an enclosing frame draws its position.
    pub struct Scroll {}

    /// A proportional scrollbar for one axis.
    ///
    /// The owner resolves its tracks before each render and event, and passes each
    /// track with the node it scrolls. A drag stays bound to the node and track it
    /// started on. It ends when either changes, or when another node takes mouse
    /// capture.
    #[derive(Clone, Copy, Debug)]
    pub struct Scrollbar {}

    /// A multi-select widget with checkbox-style items.
    ///
    /// Items can be toggled on/off independently. The selected indices are tracked
    /// in the order they were selected, allowing for ordered selection if needed.
    /// Navigation scrolls the focused row into view after layout.
    pub struct Selector<T>
    where
        T: Label, {}

    /// A row of tabs over a set of pages, one page visible at a time.
    ///
    /// Each page is a child node. Tabs hides every page but the active one. When a
    /// switch hides the page that held focus, focus moves to the first focusable
    /// node of the new page.
    ///
    /// The bar occupies the top row of padding. It paints `tabs/bar`, each label
    /// `tabs/tab`, and the active label `tabs/tab/active`, or
    /// `tabs/tab/active/focused` while focus is within the tabs.
    #[derive(Default)]
    pub struct Tabs {}

    /// Multiline text widget with wrapping and scrolling.
    pub struct Text {}

    /// Policy for publishing an input value in semantic snapshots.
    #[derive(Clone, Copy, Debug, Default, Eq, PartialEq)]
    pub enum ValueExposure {
        #[default]
        /// Omit the value from semantics.
        Omit,
        /// Publish the raw single-line value.
        Public,
        /// Mark the value as sensitive and always omit it from semantics.
        Sensitive,
    }

    /// An item that renders as one line of text.
    pub trait Label {
        /// Return the display label for this item.
        fn label(&self) -> &str;
    }

    /// Trait for widgets that can be selected in a list.
    ///
    /// Items in a `List` must implement this trait so the list can manage
    /// their selection state. Selection is independent of focus - an item
    /// remains selected even when the list loses focus.
    pub trait Selectable: Widget {
        /// Set the selection state of this item.
        fn set_selected(&mut self, selected: bool);
    }

    /// Double line Unicode box drawing set.
    pub const DOUBLE: BoxGlyphs = _;

    /// Round corner thin Unicode box drawing set.
    pub const ROUND: BoxGlyphs = _;

    /// Single line thin Unicode box drawing set.
    pub const SINGLE: BoxGlyphs = _;

    /// Single line thick Unicode box drawing set.
    pub const SINGLE_THICK: BoxGlyphs = _;

    /// Wrap `child` in a new `widget` node and return the wrapper's typed id.
    ///
    /// The child keeps its identity: it is detached from its current parent and
    /// reattached under the wrapper.
    pub fn wrap<W: 'static + Widget>(
        c: &mut dyn Context,
        child: impl Into<canopy::NodeId>,
        widget: W,
    ) -> canopy::error::Result<canopy::TypedId<W>> {
    }

    impl Border {
        /// Build a box with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Construct a box.
        pub fn new() -> Self {}

        /// Enable interior fill using the default fill style name.
        pub fn with_fill(self) -> Self {}

        /// Set the border paint role while preserving inherited component layers.
        pub fn with_border_style(self, style: impl Into<String>) -> Self {}
    }

    impl CommandNode for Border {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Widget for Border {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl Button {
        /// Build a button that dispatches a command when clicked.
        pub fn with_command(self, command: CommandCall) -> Self {}

        /// Build a button with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Construct a new button with a label.
        pub fn new(label: impl Into<String>) -> Self {}

        /// Set whether the button is active.
        pub fn set_active(&mut self, active: bool) {}

        /// Trigger the button action.
        pub fn press(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_press() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_press() -> &'static canopy::commands::CommandSpec {}
    }

    impl CommandNode for Button {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Widget for Button {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn on_mount(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl Center {
        /// Create a new Center widget.
        pub fn new() -> Self {}
    }

    impl CommandNode for Center {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Widget for Center {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl Columns {
        /// Construct columns with no panes.
        pub fn new() -> Self {}

        /// Move focus to another displayed pane by a signed offset, wrapping
        /// around.
        ///
        /// Focus moves to the pane's first focusable leaf, or to its first leaf
        /// when none accepts focus. Columns without a displayed pane do nothing.
        /// @param delta Panes to move; negative values move left.
        pub fn focus_column(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus_column(delta: i32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus_column() -> &'static canopy::commands::CommandSpec {}
    }

    impl CommandNode for Columns {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Widget for Columns {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn owns_scrollbars(&self) -> bool {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl CommandNode for Frame {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Frame {
        /// Build a frame with a specified glyph set.
        pub fn with_glyphs(self, glyphs: BoxGlyphs) -> Self {}

        /// Build a frame with a specified title.
        pub fn with_title(self, title: impl Into<String>) -> Self {}

        /// Construct a frame.
        pub fn new() -> Self {}

        /// Replace the title.
        pub fn set_title(&mut self, title: impl Into<String>) {}
    }

    impl Widget for Frame {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn owns_scrollbars(&self) -> bool {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl CommandNode for ImageView {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl ImageView {
        #[must_use]
        /// Create an image view with nothing to show yet.
        ///
        /// The view holds a single transparent pixel until [`Self::set_image`] or
        /// [`Self::set_path`] gives it real content. Callers that mount a viewer
        /// before they have an image should keep it hidden until then.
        pub fn empty() -> Self {}

        /// Create a new image view widget from a file path.
        pub fn from_path(path: impl AsRef<Path>) -> Result<Self> {}

        /// Create a new image view widget.
        pub fn new(image: &RgbaImage) -> Self {}

        /// Load a thumbnail within `bounds`, preserving its aspect ratio.
        ///
        /// Small images keep their original pixels. Larger images are averaged
        /// after compositing transparency onto black. Zooming uses the thumbnail;
        /// use [`Self::set_path`] to retain full-resolution zooming instead.
        ///
        /// The source is limited to 32 * 1024 * 1024 pixels and the decoder has a
        /// 128 MiB allocation budget. Conversion can allocate one additional RGBA
        /// source buffer. Each thumbnail edge is capped at 1024 pixels, even when
        /// `bounds` is larger. Sampling tables use at most 24 * (width + 1) *
        /// (height + 1) bytes for the thumbnail dimensions. Zero bounds are
        /// invalid. On failure, the current image is preserved. Callers should
        /// also bound the encoded file size.
        pub fn set_preview_path(&mut self, path: impl AsRef<Path>, bounds: Size) -> Result<()> {}

        /// Pan by one step in the specified direction.
        /// @param dir The pan direction.
        pub fn pan(&mut self, ctx: &mut dyn Context, dir: FocusDirection) -> Result<()> {}

        /// Show a different image, returning the view to its auto-fitted state.
        pub fn set_image(&mut self, image: &RgbaImage) {}

        /// Show the image at `path`, returning the view to its auto-fitted state.
        ///
        /// The view keeps its current image when the file cannot be read.
        pub fn set_path(&mut self, path: impl AsRef<Path>) -> Result<()> {}

        /// Zoom around the view center.
        /// @param dir The zoom direction.
        pub fn zoom(&mut self, ctx: &mut dyn Context, dir: ZoomDirection) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_pan(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_zoom(dir: ZoomDirection) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_pan() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_zoom() -> &'static canopy::commands::CommandSpec {}
    }

    impl Loader for ImageView {
        /// Register commands for the image viewer widget.
        fn load(cnpy: &mut Canopy) -> Result<()> {}
    }

    impl Widget for ImageView {
        /// Accept focus so key bindings apply to this widget.
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        /// Fill the available space in the terminal view.
        fn layout(&self) -> Layout {}

        /// Render the current image view into the terminal buffer.
        fn render(&mut self, render: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn canvas(&self, view: Size, _ctx: &CanvasContext<'_>) -> Size {}
    }

    impl CommandNode for Input {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Input {
        /// Configure whether semantic snapshots expose this input's value.
        pub fn with_value_exposure(self, exposure: ValueExposure) -> Self {}

        /// Construct a new input with initial text.
        pub fn new(txt: impl Into<String>) -> Self {}

        /// Delete a character at the input location.
        pub fn backspace(&mut self, _c: &mut dyn Context) {}

        /// Move the cursor left.
        pub fn left(&mut self, _c: &mut dyn Context) {}

        /// Move the cursor right.
        pub fn right(&mut self, _c: &mut dyn Context) {}

        /// Replace the input value and reset the cursor.
        pub fn set_value(&mut self, value: impl Into<String>) {}

        /// Return the raw input value without padding.
        pub fn value(&self) -> &str {}

        /// Set the semantic label without changing the displayed value.
        pub fn with_label(self, label: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_backspace() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_left() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_right() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_backspace() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_left() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_right() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Input {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn cursor(&self) -> Option<cursor::Cursor> {}

        fn layout(&self) -> Layout {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, _ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, r: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, _ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl CommandNode for Pad {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Pad {
        /// Create a pad with the provided edge padding.
        pub fn new(padding: Edges) -> Self {}

        /// Create a pad with uniform padding on all sides.
        pub fn uniform(padding: u32) -> Self {}
    }

    impl Widget for Pad {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl CommandNode for Root {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Loader for Root {
        fn load(c: &mut Canopy) -> Result<()> {}
    }

    impl Root {
        /// Construct a root widget wrapping the application and inspector nodes.
        pub fn new() -> Self {}

        /// Dump diagnostic information about the tree, focus, and bindings.
        pub fn dump_diagnostics(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Exit from the program, restoring terminal state. If help or inspector is
        /// open, close them first.
        pub fn quit(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Hide the help modal.
        pub fn hide_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Hide the inspector.
        pub fn hide_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// If we're currently focused in the inspector, shift focus into the app
        /// pane instead.
        pub fn focus_app(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Install the application, shared help, and enabled developer tools.
        pub fn install<W>(self, canopy: &mut Canopy, app: W) -> Result<TypedId<W>>
        where
            W: 'static + Widget, {
        }

        /// Move focus in the specified direction.
        /// @param direction The direction to move focus.
        pub fn focus(&mut self, c: &mut dyn Context, direction: FocusDirection) -> Result<()> {}

        /// Show the help modal with contextual bindings and commands.
        pub fn show_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Show the inspector.
        pub fn show_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Start with the inspector open.
        pub fn with_inspector(self, state: bool) -> Self {}

        /// Toggle help modal visibility.
        pub fn toggle_help(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Toggle inspector visibility.
        pub fn toggle_inspector(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_dump_diagnostics() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus(direction: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_focus_app() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_hide_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_hide_inspector() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_quit() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_show_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_show_inspector() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle_help() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle_inspector() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_dump_diagnostics() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_focus_app() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_hide_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_hide_inspector() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_quit() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_show_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_show_inspector() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle_help() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle_inspector() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Root {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl CommandNode for Tabs {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Tabs {
        /// Activate the tab at `index`, clamped to the last tab.
        pub fn select(&mut self, c: &mut dyn Context, index: usize) -> Result<()> {}

        /// Add `page` under a new tab at the end of the bar and return its node.
        ///
        /// The first page added is active. Later pages start hidden.
        pub fn add_tab<W: 'static + Widget>(
            &mut self,
            c: &mut dyn Context,
            label: impl Into<String>,
            page: W,
        ) -> Result<TypedId<W>> {
        }

        /// Construct tabs with no pages.
        pub fn new() -> Self {}

        /// Move the active tab by a signed offset, wrapping around.
        pub fn select_by(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Return the index of the active tab.
        pub fn active(&self) -> usize {}

        /// Build a positional call with typed user arguments.
        pub fn call_select(index: usize) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_select() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Tabs {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl CommandNode for Text {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Selectable for Text {
        fn set_selected(&mut self, selected: bool) {}
    }

    impl Text {
        /// Add a fixed width for wrapping.
        pub fn with_wrap_width(self, width: u32) -> Self {}

        /// Configure the canvas width behavior.
        pub fn with_canvas_width(self, width: CanvasWidth) -> Self {}

        /// Construct a text widget with raw content.
        pub fn new(raw: impl Into<String>) -> Self {}

        /// Page vertically through the text.
        /// Positive values move down; negative values move up.
        /// @param delta Signed page delta. Positive moves down and negative moves
        /// up.
        pub fn page(&mut self, c: &mut dyn Context, delta: i32) {}

        /// Replace the raw text content.
        pub fn set_text(&mut self, raw: impl Into<String>) {}

        /// Scroll by one line in the specified direction.
        /// @param dir The direction to scroll.
        pub fn scroll(&mut self, c: &mut dyn Context, dir: FocusDirection) {}

        /// Scroll to an absolute content position.
        pub fn scroll_to(&mut self, c: &mut dyn Context, x: u32, y: u32) {}

        /// Set the tab stop width for tab expansion.
        pub fn with_tab_stop(self, tab_stop: usize) -> Self {}

        /// Set the text rendering style when selected.
        pub fn with_selected_style(self, style: impl Into<String>) -> Self {}

        /// Set the text rendering style.
        pub fn with_style(self, style: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll_to(x: u32, y: u32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll_to() -> &'static canopy::commands::CommandSpec {}
    }

    impl Widget for Text {
        fn canvas(&self, view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl Container {
        #[must_use]
        /// Name this node's path segment.
        pub fn with_name(self, name: &str) -> Self {}

        /// Construct a container with any layout.
        pub fn new(layout: Layout) -> Self {}

        /// Fill the available space and overlap children, the last on top.
        pub fn stack() -> Self {}

        /// Fill the available space and place children in a row.
        pub fn row() -> Self {}

        /// Fill the available space and stack children in a column.
        pub fn column() -> Self {}
    }

    impl Widget for Container {
        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl Scroll {
        /// Place children in a row that scrolls horizontally.
        pub fn horizontal() -> Self {}

        /// Stack children in a column that scrolls on both axes.
        pub fn both() -> Self {}

        /// Stack children in a column that scrolls vertically.
        pub fn vertical() -> Self {}
    }

    impl Widget for Scroll {
        fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}
    }

    impl Scrollbar {
        #[must_use]
        /// Also draw the track around the thumb with `style` and `glyph`.
        pub const fn with_track(self, style: &'static str, glyph: char) -> Self {}

        #[must_use]
        /// Draw the thumb with `style` while a drag holds it.
        pub const fn with_active(self, style: &'static str) -> Self {}

        /// Construct a horizontal scrollbar whose thumb uses `style` and `glyph`.
        pub const fn horizontal(style: &'static str, glyph: char) -> Self {}

        /// Construct a vertical scrollbar whose thumb uses `style` and `glyph`.
        pub const fn vertical(style: &'static str, glyph: char) -> Self {}

        /// Draw the thumb of each track's node.
        ///
        /// `tracks` pairs each node with its track, in the outer coordinates of
        /// the context's node. A node that shows its whole canvas draws nothing.
        /// Rendering cannot release mouse capture, so a drag whose node or track
        /// has changed draws no active thumb and ends at the next event.
        pub fn render(
            &mut self,
            render: &mut Render<'_>,
            ctx: &dyn ViewContext,
            tracks: &[(NodeId, Rect)],
        ) -> Result<()> {
        }

        /// Handle a mouse event for the scrollbars drawn in `tracks`.
        ///
        /// `tracks` holds the tracks resolved for this event, as passed to
        /// [`Scrollbar::render`]. A press on a track captures the mouse for the
        /// context's node and the release frees it. Returns
        /// [`EventOutcome::Handle`] for events the scrollbar uses.
        pub fn handle_mouse(
            &mut self,
            ctx: &mut dyn Context,
            event: &mouse::MouseEvent,
            tracks: &[(NodeId, Rect)],
        ) -> Result<EventOutcome> {
        }
    }

    impl ToArgValue for AutoKey {
        fn to_arg_value(self) -> ArgValue {}
    }

    impl<T> CommandNode for Dropdown<T>
    where
        T: 'static + Label,
    {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<T> Dropdown<T>
    where
        T: 'static + Label,
    {
        /// Collapse without changing selection.
        pub fn cancel(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Confirm the highlighted selection and collapse.
        pub fn confirm(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Create a new dropdown with the given items.
        ///
        /// Returns an error if `items` is empty.
        pub fn new(items: Vec<T>) -> Result<Self> {}

        /// Get the currently selected index.
        pub fn selected_index(&self) -> usize {}

        /// Get the currently selected item.
        pub fn selected(&self) -> &T {}

        /// Move highlight by a signed offset (when expanded).
        pub fn select_by(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Toggle the dropdown expanded state.
        pub fn toggle(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_cancel() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_confirm() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_cancel() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_confirm() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle() -> &'static canopy::commands::CommandSpec {}
    }

    impl<T> Widget for Dropdown<T>
    where
        T: 'static + Label,
    {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, _view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl<T> CommandNode for Selector<T>
    where
        T: 'static + Label,
    {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<T> Selector<T>
    where
        T: 'static + Label,
    {
        /// Clear all selections.
        pub fn clear(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Create a new selector with the given items.
        pub fn new(items: Vec<T>) -> Self {}

        /// Get references to the selected items in selection order.
        pub fn selected_items(&self) -> Vec<&T> {}

        /// Move focus by a signed offset.
        pub fn select_by(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move focus to the first item.
        pub fn select_first(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Move focus to the last item.
        pub fn select_last(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Select all items.
        pub fn select_all(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Toggle selection of the focused item.
        pub fn toggle(&mut self, _c: &mut dyn Context) -> Result<()> {}

        /// Build a positional call with typed user arguments.
        pub fn call_clear() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_all() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_first() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_last() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_toggle() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_all() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_first() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_last() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_toggle() -> &'static canopy::commands::CommandSpec {}
    }

    impl<T> Widget for Selector<T>
    where
        T: 'static + Label,
    {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, _view: Size, _ctx: &canopy::layout::CanvasContext<'_>) -> Size {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }

    impl<W: 'static + Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> Widget for List<W, K> {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn canvas(&self, view: Size, ctx: &CanvasContext<'_>) -> Size {}

        fn layout(&self) -> Layout {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn on_event(&mut self, event: &Event, ctx: &mut dyn Context) -> Result<EventOutcome> {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}

        fn semantics(&self, ctx: &dyn ViewContext) -> Result<WidgetSemantics> {}
    }

    impl<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> CommandNode for List<W, K> {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl<W: Selectable, K: 'static + Clone + Eq + Hash + ToArgValue> List<W, K> {
        /// Borrow the stable keys in display order.
        pub fn keys(&self) -> &[K] {}

        /// Build a list that dispatches a command when a row is activated.
        pub fn with_on_activate(self, command: CommandCall) -> Self {}

        /// Build a list with a list-level selection indicator.
        /// Repeat controls whether the indicator renders on every visible line.
        pub fn with_selection_indicator(
            self,
            style: impl Into<String>,
            text: impl Into<String>,
            repeat: bool,
        ) -> Self {
        }

        /// Clear all items from the list.
        pub fn clear(&mut self, ctx: &mut dyn Context) -> Result<()> {}

        /// Construct an empty list.
        pub fn new() -> Self {}

        /// Delete the currently selected item.
        pub fn delete_selected(&mut self, ctx: &mut dyn Context) -> Result<bool> {}

        /// Move selection by a signed offset.
        pub fn select_by(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move selection by one page.
        /// Positive values move down; negative values move up. Zero is a no-op.
        /// @param delta Signed page delta. Positive moves down and negative moves
        /// up.
        pub fn page(&mut self, c: &mut dyn Context, delta: i32) -> Result<()> {}

        /// Move selection to the first item.
        pub fn select_first(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Move selection to the last item.
        pub fn select_last(&mut self, c: &mut dyn Context) -> Result<()> {}

        /// Reconcile domain keys while retaining widgets and selection for
        /// surviving keys.
        ///
        /// Duplicate keys fail before callbacks run. Updates have the same
        /// structural rollback boundary as [`KeyedChildren::reconcile`]. If
        /// selection is removed, the next surviving old neighbor wins, then the
        /// previous neighbor.
        pub fn reconcile<I, C, U>(
            &mut self,
            ctx: &mut dyn Context,
            desired: I,
            create: C,
            update: U,
        ) -> Result<Vec<TypedId<W>>>
        where
            C: FnMut(&K) -> Result<W>,
            I: IntoIterator<Item = K>,
            U: FnMut(&K, TypedId<W>, &mut dyn Context) -> Result<()>, {
        }

        /// Return the stable key of the selected row.
        pub fn selected_key(&self) -> Option<&K> {}

        /// Returns the currently selected index.
        pub fn selected_index(&self) -> Option<usize> {}

        /// Returns the number of items in the list.
        pub fn len(&self) -> usize {}

        /// Returns the typed ID of the currently selected item.
        pub fn selected_item(&self) -> Option<TypedId<W>> {}

        /// Returns the typed ID of the item at the given index.
        pub fn item(&self, index: usize) -> Option<TypedId<W>> {}

        /// Returns true if the list is empty.
        pub fn is_empty(&self) -> bool {}

        /// Scroll the view by one line in the specified direction.
        /// @param dir The direction to scroll.
        pub fn scroll(&mut self, c: &mut dyn Context, dir: FocusDirection) {}

        /// Select a domain key, returning an error when it is absent.
        pub fn select_key(&mut self, ctx: &mut dyn Context, key: &K) -> Result<()> {}

        /// Select an item at the given index.
        pub fn select(&mut self, ctx: &mut dyn Context, index: usize) -> Result<()> {}

        /// Set the semantic label of the collection.
        pub fn with_label(self, label: impl Into<String>) -> Self {}

        /// Build a positional call with typed user arguments.
        pub fn call_clear() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_delete_selected() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_page(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_scroll(dir: FocusDirection) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_by(delta: i32) -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_first() -> canopy::commands::CommandCall {}

        /// Build a positional call with typed user arguments.
        pub fn call_select_last() -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_clear() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_delete_selected() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_page() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_scroll() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_by() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_first() -> &'static canopy::commands::CommandSpec {}

        /// Return a typed command reference for this command.
        pub fn cmd_select_last() -> &'static canopy::commands::CommandSpec {}
    }

    impl<W: Selectable> List<W, AutoKey> {
        /// Append a widget with a fresh automatic key.
        pub fn append(&mut self, ctx: &mut dyn Context, widget: W) -> Result<TypedId<W>> {}

        /// Insert a widget with a fresh automatic key at the clamped index.
        pub fn insert(
            &mut self,
            ctx: &mut dyn Context,
            index: usize,
            widget: W,
        ) -> Result<TypedId<W>> {
        }
    }
}
