// @generated by `ruskel-snapshot`; do not edit.

pub mod hello {
    //! Minimal Canopy application, and the reference for building one outside the
    //! Canopy workspace.
    //!
    //! The crate shows the whole external contract in one place: a widget with a
    //! command, a [`CanopyBuilder`] pipeline, an optional trusted user
    //! configuration directory, and a factory that every launch mode shares.

    /// A greeting and a counter driven by one command.
    pub struct Hello {}

    /// Default configuration: the startup script that runs when the user has no
    /// `init.luau`, and the file a first run writes for them to edit.
    pub const DEFAULT_CONFIG: &str = "-- Hello\'s default configuration.\n--\n-- Hello reads ~/.hello/init.luau when that file exists, and uses these defaults\n-- otherwise. The first interactive run writes them there for you to edit. Set\n-- HELLO_CONFIG_HOME to read the file from another directory.\n\nfunction setup()\n    root.default_bindings()\n\n    canopy.keymap({\n        { key = \"+\", description = \"Count up\", action = command.hello.bump(1) },\n        { key = \"-\", description = \"Count down\", action = command.hello.bump(-1) },\n    })\nend\n";

    /// Create the full Canopy application.
    ///
    /// A `home` holding `init.luau` is mounted as the trusted user configuration;
    /// otherwise the application runs [`DEFAULT_CONFIG`]. Headless and API launch
    /// modes pass `None` so they never read user state.
    pub fn create_app(
        home: Option<&canopy_mcp::ConfigHome>,
    ) -> canopy::error::Result<canopy::Canopy> {
    }

    impl CommandNode for Hello {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Hello {
        /// Add a signed amount to the counter.
        /// @param delta Negative values count down; positive values count up.
        pub fn bump(&mut self, delta: i32) {}

        /// Build a positional call with typed user arguments.
        pub fn call_bump(delta: i32) -> canopy::commands::CommandCall {}

        /// Return the command spec for this command.
        pub fn spec_bump() -> &'static canopy::commands::CommandSpec {}
    }

    impl Register for Hello {
        fn register(setup: &mut Setup) -> Result<()> {}
    }

    impl Widget for Hello {
        fn accept_focus(&self, _context: &dyn ViewContext) -> bool {}

        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_mount(&mut self, context: &mut dyn Context) -> Result<()> {}

        fn render(&mut self, render: &mut Render<'_>, context: &dyn ViewContext) -> Result<()> {}
    }
}
