// @generated by `ruskel-snapshot`; do not edit.
//
// Package: hello
// Publish: no
// Binaries: hello
// Workspace dependencies: canopy, canopy-mcp, canopy-widgets
// Workspace dependents: none

//! Minimal Canopy application, and the reference for building one outside the
//! Canopy workspace.
//!
//! The crate shows the whole external contract in one place: a widget with a
//! command, a [`CanopyBuilder`] pipeline, an optional trusted user
//! configuration directory, and a factory that every launch mode shares.

use canopy::{
    Canopy, Register, Widget,
    commands::{CommandCall, CommandNode, CommandSpec},
};
use canopy_mcp::ConfigHome;

/// A greeting and a counter driven by one command.
pub struct Hello {/* private fields */}

impl Hello {
    /// Add a signed amount to the counter.
    /// @param delta Negative values count down; positive values count up.
    pub fn bump(&mut self, delta: i32);
}

impl Hello {
    /// Build a positional call with typed user arguments.
    pub fn call_bump(delta: i32) -> CommandCall;

    /// Return the command spec for this command.
    pub fn spec_bump() -> &'static CommandSpec;
}

impl CommandNode for Hello {}

impl Register for Hello {}

impl Widget for Hello {}

/// Create the full Canopy application.
///
/// A `home` holding `init.luau` is mounted as the trusted user configuration;
/// otherwise the application runs [`DEFAULT_CONFIG`]. Headless and API launch
/// modes pass `None` so they never read user state.
pub fn create_app(home: Option<&ConfigHome>) -> canopy::error::Result<Canopy>;

/// Default configuration: the startup script that runs when the user has no
/// `init.luau`, and the file a first run writes for them to edit.
pub const DEFAULT_CONFIG: &str = "-- Hello\'s default configuration.\n--\n-- Hello reads ~/.hello/init.luau when that file exists, and uses these defaults\n-- otherwise. The first interactive run writes them there for you to edit. Set\n-- HELLO_CONFIG_HOME to read the file from another directory.\n\nfunction setup()\n    root.default_bindings()\n\n    canopy.keymap({\n        { key = \"+\", description = \"Count up\", action = command.hello.bump(1) },\n        { key = \"-\", description = \"Count down\", action = command.hello.bump(-1) },\n    })\nend\n";
