// @generated by `ruskel-snapshot`; do not edit.

pub mod hello {
    //! Minimal Canopy application, and the reference for building one outside the
    //! Canopy workspace.
    //!
    //! The crate shows the whole external contract in one place: a widget with a
    //! command, a [`CanopyBuilder`] pipeline, an optional trusted user
    //! configuration directory, and a factory that every launch mode shares.

    /// A greeting and a counter driven by one command.
    pub struct Hello {}

    /// Default keymap copied to a user's configuration directory on first use.
    pub const DEFAULT_BINDINGS: &str = "root.default_bindings()\n\ncanopy.bind(\"?\", {\n    path = \"/root/**/\",\n    phase = \"before_widget\",\n    tier = \"global\",\n    description = \"Show key bindings\",\n}, command.root.toggle_help())\n\ncanopy.keymap({\n    { key = \"+\", description = \"Count up\", action = command.hello.bump(1) },\n    { key = \"-\", description = \"Count down\", action = command.hello.bump(-1) },\n})\n";

    /// Startup module that loads the editable user keymap.
    pub const DEFAULT_INIT: &str = r#"local bindings = require("./bindings")

function setup()
    bindings.setup()
end
"#;

    /// Create the full Canopy application.
    ///
    /// Pass `Some(root)` to mount a trusted user configuration directory, and
    /// `None` to fall back to the compiled-in defaults. Headless and API launch
    /// modes must always pass `None` so they never read or create user state.
    pub fn create_app(
        user_script_root: Option<std::path::PathBuf>,
    ) -> canopy::error::Result<canopy::Canopy> {
    }

    /// Create the default user config without replacing existing files.
    ///
    /// A first run writes `init.luau` and `bindings.luau`. Every later run leaves
    /// whatever the user has since edited in place.
    pub fn ensure_user_config(root: &std::path::Path) -> io::Result<()> {}

    impl CommandNode for Hello {
        fn commands() -> &'static [&'static canopy::commands::CommandSpec] {}
    }

    impl Hello {
        /// Add a signed amount to the counter.
        /// @param delta Negative values count down; positive values count up.
        pub fn bump(&mut self, delta: i32) {}

        /// Build a positional call with typed user arguments.
        pub fn call_bump(delta: i32) -> canopy::commands::CommandCall {}

        /// Return a typed command reference for this command.
        pub fn cmd_bump() -> &'static canopy::commands::CommandSpec {}
    }

    impl Loader for Hello {
        fn load(canopy: &mut Canopy) -> Result<()> {}
    }

    impl Widget for Hello {
        fn accept_focus(&self, _context: &dyn ViewContext) -> bool {}

        fn layout(&self) -> Layout {}

        fn name(&self) -> NodeName {}

        fn on_mount(&mut self, context: &mut dyn Context) -> Result<()> {}

        fn render(&mut self, render: &mut Render<'_>, context: &dyn ViewContext) -> Result<()> {}
    }
}
