// @generated by `ruskel-snapshot`; do not edit.

pub mod todo {
    //! Todo application used as Canopy's end-to-end example and smoke-test target.

    pub mod store {
        //! SQLite storage for the todo example.

        /// Cloneable handle to one todo database.
        pub struct Store {}

        /// A persisted todo record.
        pub struct Todo {
            /// Database identifier.
            pub id: i64,
            /// User-provided todo text.
            pub item: String,
        }

        impl Clone for Store {
            fn clone(&self) -> Store {}
        }

        impl Debug for Store {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }

        impl Store {
            /// Load every persisted todo.
            pub fn todos(&self) -> Result<Vec<Todo>> {}

            /// Open or initialize a SQLite store.
            pub fn open(path: &str) -> Result<Self> {}
        }

        impl Clone for Todo {
            fn clone(&self) -> Todo {}
        }

        impl Debug for Todo {
            fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {}
        }
    }

    /// Widget for a todo entry.
    pub struct TodoEntry {}

    /// Build the todo command and fixture API without assembling a widget tree.
    pub fn api_app() -> canopy::error::Result<canopy::Canopy> {}

    /// Create a todo application with an explicit database and optional user
    /// config.
    pub fn create_app(
        store: store::Store,
        config: Option<&std::path::Path>,
    ) -> anyhow::Result<canopy::Canopy> {
    }

    impl Selectable for TodoEntry {
        fn set_selected(&mut self, selected: bool) {}
    }

    impl Widget for TodoEntry {
        fn accept_focus(&self, _ctx: &dyn ViewContext) -> bool {}

        fn layout(&self) -> Layout {}

        fn measure(&self, c: MeasureConstraints) -> Measurement {}

        fn name(&self) -> NodeName {}

        fn render(&mut self, rndr: &mut Render<'_>, ctx: &dyn ViewContext) -> Result<()> {}
    }
}
