on: [push, pull_request]

jobs:
    test:
        name: canopy - ${{ matrix.os }} ${{ matrix.toolchain }}
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                - { toolchain: stable, os: ubuntu-latest }
                - { toolchain: nightly, os: ubuntu-latest }
                - { toolchain: stable, os: windows-latest }
                - { toolchain: nightly, os: windows-latest }
        steps:
            - uses: actions/checkout@v3
            - uses: dtolnay/rust-toolchain@master
              with:
                    toolchain: ${{ matrix.toolchain }}
            - run: cargo test --all-features
